<?php
/**
 * Catálogos CHV (Fracción III - Cheques de viajero).
 *
 * Base tomada del instructivo_chv.xlsx. Los catálogos tipo_operacion y
 * tipo_alerta quedan listos para ajustar con claves oficiales del XSD/XML.
 */

require_once __DIR__ . '/din_catalogos.php';
if (file_exists(__DIR__ . '/tsc_catalogos.php')) {
    require_once __DIR__ . '/tsc_catalogos.php';
}

if (!isset($CHV_CATALOGOS) || !is_array($CHV_CATALOGOS)) {
    $CHV_CATALOGOS = [];
}

$CHV_CATALOGOS['clave_actividad'] = [
    'CHV' => 'Emisión y comercialización habitual o profesional de cheques de viajero',
];

$CHV_CATALOGOS['prioridad'] = [
    '1' => '1 - Normal',
    '2' => '2 - 24 horas con operaciones',
];

$CHV_CATALOGOS['exento'] = [
    '0' => 'No',
    '1' => 'Sí',
];

$CHV_CATALOGOS['tipo_operacion'] = [
    '301' => 'Venta de Cheques de Viajero',
    '303' => 'Emisión de Cheques de Viajero',
];

$CHV_CATALOGOS['moneda_cheques'] = [
    '1' => 'Dólar estadounidense',
    '2' => 'Dólar canadiense',
    '3' => 'Dólar australiano',
    '4' => 'Libra esterlina',
    '5' => 'Euro',
    '6' => 'Yen japonés',
    '9' => 'Otros',
];

$CHV_CATALOGOS['tipo_alerta'] = [
    '100' => 'Sin alerta',
    '301' => 'El cliente o usuario realiza operaciones de compra o venta de cheques de viajero de forma periódica sin razón aparente',
    '302' => 'El cliente o usuario realiza la operación de compra o venta de cheques de viajero por monto elevados llevando a cabo su liquidando en efectivo',
    '303' => 'El cliente o usuario realiza diversas operación de compra o venta de cheques de viajero por montos elevados en un periodo corto de tiempo sin justificación aparente',
    '304' => 'El cliente o usuario se rehúsa a proporcionar documentos personales que lo identifiquen',
    '305' => 'Se conoce un historial criminal del cliente o usuario, de algún familiar directo o persona relacionada con él',
    '306' => 'De acuerdo con la ocupación del cliente o usuario, el monto de compra o venta de cheques de viajero parece estar fuera de su alcance',
    '307' => 'De acuerdo con los ingresos declarados por el cliente o usuario, el monto de compra o venta de cheques de viajero parece estar fuera de su alcance',
    '308' => 'Hay indicios, o certeza, que las partes no están actuando en nombre propio y están tratando de ocultar la identidad del cliente o usuario real',
    '309' => 'Uso de divisas en efectivo en montos elevados o de poco uso sin que la ocupación del cliente o usuario lo justifique',
    '310' => 'El cliente o usuario intenta sobornar o extorsionar al vendedor con el fin de realizar la operación de forma irregular',
    '311' => 'El cliente o usuario solicita condiciones especiales poco usuales en la realización de la operación',
    '312' => 'El cliente o usuario proporcionó datos falsos o documentos apócrifos al realizar la operación',
    '313' => 'El cliente o usuario no quiere ser relacionado con la operación realizada',
    '314' => 'El cliente o usuario muestra fuerte interés en la realización de la transacción con rapidez, sin que exista causa justificada',
    '315' => 'La operación se liquida por medio de una transferencia internacional sin que la ocupación, perfil o nacionalidad del cliente o usuario lo justifique',
    '316' => 'La operación se liquida por medio de una transferencia internacional proveniente de un país considerado como paraíso fiscal o de alto riesgo',
    '317' => 'Operaciones con organizaciones sin fines de lucro, cuando las características de la transacción no coinciden con los objetivos de la entidad',
    '9999' => 'Otra alerta',
];

$CHV_CATALOGOS['instrumento_monetario'] = [
    '1' => 'Efectivo',
    '2' => 'Tarjeta de Crédito',
    '3' => 'Tarjeta de Débito',
    '4' => 'Tarjeta de Prepago',
    '5' => 'Cheque Nominativo',
    '6' => 'Cheque de Caja',
    '7' => 'Cheques de Viajero',
    '8' => 'Transferencia Interbancaria',
    '9' => 'Transferencia Misma Institución',
    '10' => 'Transferencia Internacional',
    '11' => 'Orden de Pago',
    '12' => 'Giro',
    '13' => 'Oro o Platino Amonedados',
    '14' => 'Plata Amonedada',
    '15' => 'Metales Preciosos',
    '16' => 'Activos Virtuales',
];

$CHV_CATALOGOS['moneda'] = [
    '1' => 'MXN - Peso mexicano - México',
    '2' => 'USD - Dólar estadounidense - Estados Unidos',
    '3' => 'EUR - Euro - Unión Europea',
    '4' => 'AED - Dirham de los Emiratos Árabes Unidos - Emiratos Árabes Unidos',
    '5' => 'AFN - Afgani afgano - Afganistán',
    '6' => 'ALL - Lek albanés - Albania',
    '7' => 'AMD - Dram armenio - Armenia',
    '8' => 'ANG - Florín antillano neerlandés - Antillas Neerlandesas',
    '9' => 'AOA - Kwanza angoleño - Angola',
    '10' => 'ARS - Peso argentino - Argentina',
    '11' => 'AUD - Dólar australiano - Australia',
    '12' => 'AWG - Florín arubeño - Aruba',
    '13' => 'AZN - Manat azerbaiyano - Azerbaiyán',
    '14' => 'BAM - Marco convertible de Bosnia-Herzegovina - Bosnia y Herzegovina',
    '15' => 'BBD - Dólar de Barbados - Barbados',
    '16' => 'BDT - Taka de Bangladesh - Bangladesh',
    '17' => 'BGN - Lev búlgaro - Bulgaria',
    '18' => 'BHD - Dinar bahreiní - Bahréin',
    '19' => 'BIF - Franco burundés - Burundi',
    '20' => 'BMD - Dólar de Bermuda - Bermudas',
    '21' => 'BND - Dólar de Brunéi - Brunéi',
    '22' => 'BOB - Boliviano - Bolivia',
    '23' => 'BRL - Real brasileño - Brasil',
    '24' => 'BSD - Dólar bahameño - Bahamas',
    '25' => 'BTN - Ngultrum de Bután - Bután',
    '26' => 'BWP - Pula de Botsuana - Botsuana',
    '27' => 'BYR - Rublo bielorruso - Bielorrusia',
    '28' => 'BZD - Dólar de Belice - Belice',
    '29' => 'CAD - Dólar canadiense - Canadá',
    '30' => 'CDF - Franco congoleño - República Democrática del Congo',
    '31' => 'CHF - Franco suizo - Suiza',
    '32' => 'CLP - Peso chileno - Chile',
    '33' => 'CNY - Yuan chino - China',
    '34' => 'COP - Peso colombiano - Colombia',
    '35' => 'CRC - Colón costarricense - Costa Rica',
    '36' => 'CSD - Dinar serbio - Serbia',
    '37' => 'CUC - Peso cubano convertible - Cuba',
    '38' => 'CUP - Peso cubano - Cuba',
    '39' => 'CVE - Escudo caboverdiano - Cabo Verde',
    '40' => 'CZK - Corona checa - República Checa',
    '41' => 'DJF - Franco yibutiano - Yibuti',
    '42' => 'DKK - Corona danesa - Dinamarca',
    '43' => 'DOP - Peso dominicano - República Dominicana',
    '44' => 'DZD - Dinar argelino - Argelia',
    '45' => 'EGP - Libra egipcia - Egipto',
    '46' => 'ERN - Nakfa eritreo - Eritrea',
    '47' => 'ETB - Birr etíope - Etiopía',
    '48' => 'FJD - Dólar fiyiano - Fiji',
    '49' => 'FKP - Libra malvinense - Islas Malvinas',
    '50' => 'GBP - Libra esterlina - Reino Unido',
    '51' => 'GEL - Lari georgiano - Georgia',
    '52' => 'GHS - Cedi ghanés - Ghana',
    '53' => 'GIP - Libra de Gibraltar - Gibraltar',
    '54' => 'GMD - Dalasi gambiano - Gambia',
    '55' => 'GNF - Franco guineano - Guinea',
    '56' => 'GTQ - Quetzal guatemalteco - Guatemala',
    '57' => 'GYD - Dólar guyanés - Guyana',
    '58' => 'HKD - Dólar de Hong Kong - Hong Kong',
    '59' => 'HNL - Lempira hondureño - Honduras',
    '60' => 'HRK - Kuna croata - Croacia',
    '61' => 'HTG - Gourde haitiano - Haití',
    '62' => 'HUF - Forint húngaro - Hungría',
    '63' => 'IDR - Rupiah indonesia - Indonesia',
    '64' => 'ILS - Nuevo shéquel israelí - Israel',
    '65' => 'INR - Rupia india - India',
    '66' => 'IQD - Dinar iraquí - Irak',
    '67' => 'IRR - Rial iraní - Irán',
    '68' => 'ISK - Corona islandesa - Islandia',
    '69' => 'JMD - Dólar jamaiquino - Jamaica',
    '70' => 'JOD - Dinar jordano - Jordania',
    '71' => 'JPY - Yen japonés - Japón',
    '72' => 'KES - Chelín keniano - Kenia',
    '73' => 'KGS - Som kirguís - Kirguistán',
    '74' => 'KHR - Riel camboyano - Camboya',
    '75' => 'KMF - Franco comoriano - Comoras',
    '76' => 'KPW - Won norcoreano - Corea del Norte',
    '77' => 'KRW - Won surcoreano - Corea del Sur',
    '78' => 'KWD - Dinar kuwaití - Kuwait',
    '79' => 'KYD - Dólar caimano - Islas Caimán',
    '80' => 'KZT - Tenge kazajo - Kazajstán',
    '81' => 'LAK - Kip lao - Laos',
    '82' => 'LBP - Libra libanesa - Líbano',
    '83' => 'LKR - Rupia de Sri Lanka - Sri Lanka',
    '84' => 'LRD - Dólar liberiano - Liberia',
    '85' => 'LSL - Loti lesotense - Lesoto',
    '86' => 'LTL - Litas lituano - Lituania',
    '87' => 'LVL - Lat letón - Letonia',
    '88' => 'LYD - Dinar libio - Libia',
    '89' => 'MAD - Dirham marroquí - Marruecos',
    '90' => 'MDL - Leu moldavo - Moldavia',
    '91' => 'MGA - Ariary malgache - Madagascar',
    '92' => 'MKD - Denar macedonio - Macedonia',
    '93' => 'MMK - Kyat birmano - Myanmar',
    '94' => 'MNT - Tughrik mongol - Mongolia',
    '95' => 'MOP - Pataca de Macao - Macao',
    '96' => 'MRO - Ouguiya mauritana - Mauritania',
    '97' => 'MUR - Rupia mauriciana - Mauricio',
    '98' => 'MVR - Rufiyaa maldiva - Maldivas',
    '99' => 'MWK - Kwacha malauí - Malaui',
    '100' => 'MYR - Ringgit malayo - Malasia',
    '101' => 'MZN - Metical mozambiqueño - Mozambique',
    '102' => 'NAD - Dólar namibio - Namibia',
    '103' => 'NGN - Naira nigeriana - Nigeria',
    '104' => 'NIO - Córdoba nicaragüense - Nicaragua',
    '105' => 'NOK - Corona noruega - Noruega',
    '106' => 'NPR - Rupia nepalí - Nepal',
    '107' => 'NZD - Dólar neozelandés - Nueva Zelanda',
    '108' => 'OMR - Rial omaní - Omán',
    '109' => 'PAB - Balboa panameño - Panamá',
    '110' => 'PEN - Nuevo sol peruano - Perú',
    '111' => 'PGK - Kina de Papúa Nueva Guinea - Papúa Nueva Guinea',
    '112' => 'PHP - Peso filipino - Filipinas',
    '113' => 'PKR - Rupia pakistaní - Pakistán',
    '114' => 'PLN - Zloty polaco - Polonia',
    '115' => 'PYG - Guaraní paraguayo - Paraguay',
    '116' => 'QAR - Rial catarí - Qatar',
    '117' => 'RON - Leu rumano - Rumania',
    '118' => 'RSD - Dinar serbio - Serbia',
    '119' => 'RUB - Rublo ruso - Rusia',
    '120' => 'RWF - Franco ruandés - Ruanda',
    '121' => 'SAR - Riyal saudí - Arabia Saudí',
    '122' => 'SBD - Dólar de las Islas Salomón - Islas Salomón',
    '123' => 'SCR - Rupia de Seychelles - Seychelles',
    '124' => 'SDG - Dinar sudanés - Sudán',
    '125' => 'SEK - Corona sueca - Suecia',
    '126' => 'SGD - Dólar de Singapur - Singapur',
    '127' => 'SHP - Libra de Santa Helena - Santa Elena',
    '128' => 'SLL - Leone de Sierra Leona - Sierra Leona',
    '129' => 'SOS - Chelín somalí - Somalia',
    '130' => 'SRD - Dólar surinamés - Surinam',
    '131' => 'SSP - Libra de Sudán del Sur - Sudán del Sur',
    '132' => 'STD - Dobra de Santo Tomé y Príncipe - Santo Tomé y Príncipe',
    '133' => 'SVC - Colón salvadoreño - El Salvador',
    '134' => 'SYP - Libra siria - Siria',
    '135' => 'SZL - Lilangeni suazi - Suazilandia',
    '136' => 'THB - Baht tailandés - Tailandia',
    '137' => 'TJS - Somoni tayik - Tayikistán',
    '138' => 'TMT - Manat turcomano - Turkmenistán',
    '139' => 'TND - Dinar tunecino - Túnez',
    '140' => 'TOP - Paʻanga tongano - Tonga',
    '141' => 'TRY - Lira turca - Turquía',
    '142' => 'TTD - Dólar de Trinidad y Tobago - Trinidad y Tobago',
    '143' => 'TWD - Dólar taiwanés - Taiwán',
    '144' => 'TZS - Chelín tanzano - Tanzania',
    '145' => 'UAH - Grivna ucraniana - Ucrania',
    '146' => 'UGX - Chelín ugandés - Uganda',
    '147' => 'UYU - Peso uruguayo - Uruguay',
    '148' => 'UZS - Som uzbeko - Uzbekistán',
    '149' => 'VEF - Bolívar fuerte venezolano - Venezuela',
    '150' => 'VND - Dong vietnamita - Vietnam',
    '151' => 'VUV - Vatu vanuatense - Vanuatu',
    '152' => 'WST - Tala samoano - Samoa',
    '153' => 'YER - Rial yemení - Yemen',
    '154' => 'ZAR - Rand sudafricano - Sudáfrica',
    '155' => 'ZMK - Kwacha zambiano - Zambia',
    '156' => 'ZMW - Kwacha zambiano - Zambia',
    '157' => 'ZWL - Dólar zimbabuense - Zimbabue',
    '158' => 'MXA - Centenario - México',
    '159' => 'MXB - Azteca - México',
    '160' => 'MXC - Hidalgo - México',
    '161' => 'MXD - 1/2 Hidalgo - México',
    '162' => 'MXE - 1/4 Hidalgo - México',
    '163' => 'MXF - 1/5 Hidalgo - México',
    '164' => 'MXG - 1 Oz Libertad de Oro - México',
    '165' => 'MXH - 1/2 Oz Libertad de Oro - México',
    '166' => 'MXI - 1/4 Oz Libertad de Oro - México',
    '167' => 'MXJ - 1/10 Oz Libertad de Oro - México',
    '168' => 'MXK - 1/20 Oz Libertad de Oro - México',
    '169' => 'MXL - 1 Oz Libertad de Plata - México',
    '170' => 'MXM - 1/2 Oz Libertad de Plata - México',
    '171' => 'MXN - 1/4 Oz Libertad de Plata - México',
    '172' => 'MXO - 1/10 Oz Libertad de Plata - México',
    '173' => 'MXP - 1/20 Oz Libertad de Plata - México',
    '174' => 'XAG - Onza de plata - N/A',
    '175' => 'XAU - Onza de oro - N/A',
    '176' => 'XFO - Franco de oro - N/A',
    '177' => 'XPD - Onza de paladio - N/A',
    '178' => 'XPT - Onza de platino - N/A',
    '179' => 'XAF - Franco CFA de África Central - N/A',
    '180' => 'XCD - Dólar del Caribe Oriental - N/A',
    '181' => 'XFU - Franco UIC - N/A',
    '182' => 'XDR - Derecho Especial de Giro - N/A',
    '183' => 'XOF - Franco CFA de África Occidental - N/A',
    '184' => 'XPF - Franco CFP - N/A',
];

$CHV_CATALOGOS['pais'] = $TSC_CATALOGOS['pais'] ?? ($DIN_CATALOGOS['pais'] ?? []);
$CHV_CATALOGOS['actividad_economica'] = [
    '1000000' => 'NO APLICA',
    '1110100' => 'AGRICULTURA Y SILVICULTURA - ADMINISTRADORES O TRABAJADORES AGRICOLAS',
    '1110400' => 'AGRICULTURA Y SILVICULTURA - ADMINISTRADORES O TRABAJADORES SILVICOLAS Y FORESTALES',
    '1220100' => 'GANADERIA - APICULTORES',
    '1220200' => 'GANADERIA - ADMINISTRADORES, CRIADORES O SUPERVISORES AVICOLAS Y GANADEROS',
    '1330200' => 'PESCA Y ACUACULTURA - PESCADORES Y TRABAJADORES EN LA CRIA Y CULTIVO DE ESPECIES MARINAS',
    '2130100' => 'MINERIA, EXTRACCION Y SUMINISTRO - TECNICOS GEOLOGICOS Y DE MINERALES',
    '2140100' => 'MINERIA, EXTRACCION Y SUMINISTRO - INGENIEROS, OPERADORES O AYUDANTES EN LA EXTRACCION Y REFINACION MINERA',
    '2210100' => 'MINERIA, EXTRACCION Y SUMINISTRO - AYUDANTES EN LA PERFORACION DE POZOS DE PETROLEO Y GAS NATURAL',
    '2240200' => 'MINERIA, EXTRACCION Y SUMINISTRO - INGENIEROS PETROLEROS',
    '2420100' => 'MINERIA, EXTRACCION Y SUMINISTRO - OPERADORES DE CENTRALES O SISTEMAS DE ENERGIA ELECTRICAS',
    '2420200' => 'MINERIA, EXTRACCION Y SUMINISTRO - OPERADORES DE MAQUINAS DE VAPOR',
    '2530100' => 'MINERIA, EXTRACCION Y SUMINISTRO - GERENTE, SUPERVISOR U OPERADORES DE TRATAMIENTO Y POTABILIZACION, ABASTECIMIENTO Y RECOLECCION DE AGUA',
    '3130100' => 'CONSTRUCCION - DECORADORES DE INTERIORES',
    '3130300' => 'CONSTRUCCION - INGENIEROS, TECNICOS Y OPERADORES DE LA CONSTRUCCION',
    '3310300' => 'CONSTRUCCION - COLOCADORES DE PRODUCTOS PREFABRICADOS EN INMUEBLES',
    '3310400' => 'CONSTRUCCION - PINTORES',
    '3310600' => 'CONSTRUCCION - VIDRIEROS',
    '3410200' => 'CONSTRUCCION - REPARADORES DE VIAS DE COMUNICACION',
    '3420100' => 'CONSTRUCCION - PLOMEROS E INSTALADORES DE TUBERIA',
    '3420200' => 'CONSTRUCCION - ARQUITECTOS',
    '4130300' => 'MECANICA - MECANICOS DE EQUIPO PESADO',
    '4130500' => 'MECANICA - INGENIERO O MECANICOS INSTALADORES DE MAQUINARIA INDUSTRIAL',
    '4131000' => 'MECANICA - INGENIERO O TECNICO EN MECANICA DE VEHICULOS TERRESTRES, AEREOS Y ACUATICOS',
    '4230200' => 'ELECTRICIDAD - INGENIEROS O TECNICOS ELECTRICISTAS',
    '4230500' => 'ELECTRICIDAD - TECNICOS EN REFRIGERACION, AIRE ACONDICIONADO Y CALEFACCION',
    '4330100' => 'ELECTRONICA - MECANICOS DE INSTRUMENTOS INDUSTRIALES',
    '4330200' => 'ELECTRONICA - INGENIERO O TECNICOS EN ELECTRONICA',
    '4430200' => 'INFORMATICA - INGENIERO O TECNICOS PROGRAMADORES EN INFORMATICA',
    '4440100' => 'INFORMATICA - PROFESIONISTAS O TECNICOS DE SISTEMAS DE INFORMACION Y PROCESAMIENTO DE DATOS',
    '4530200' => 'TELECOMUNICACIONES - INGENIERO, INSTALADORES Y REPARADORES DE EQUIPOS Y ACCESORIOS DE TELECOMUNICACIONES',
    '4530500' => 'TELECOMUNICACIONES - TELEGRAFISTAS Y RADIO-OPERADORES',
    '4630100' => 'PROCESOS INDUSTRIALES - INGENIERO O TECNICOS INDUSTRIAL Y DE PRODUCCION',
    '4640300' => 'PROCESOS INDUSTRIALES - INGENIEROS METALURGICOS Y DE MATERIALES',
    '5110100' => 'MINERALES NO METALICOS - OPERADORES O TRABAJADORES DE VIDRIO Y CONCRETO',
    '5121300' => 'MINERALES NO METALICOS - OPERADORES DE MAQUINAS PROCESADORAS DE MINERALES NO METALICOS',
    '5210100' => 'METALES - SUPERVISORES U OPERADORES DE PROCESAMIENTO Y FUNDICION DE METALES',
    '5310700' => 'ALIMENTOS Y BEBIDAS - TRABAJADORES EN LA ELABORACION Y PROCESAMIENTO DE ALIMENTOS, BEBIDAS Y TABACO',
    '5410100' => 'TEXTILES Y PRENDAS DE VESTIR - TRABAJADORES EN LA PRODUCCION DE TEXTILES, PRENDAS DE VESTIR Y CALZADO',
    '5420700' => 'TEXTILES Y PRENDAS DE VESTIR - TRABAJADORES DE REPARACION DE PRENDAS DE VESTIR Y CALZADO',
    '5510100' => 'MADERA, PAPEL, Y PIEL - TRABAJADORES EN LA FABRICACION DE MUEBLES O PRODUCTOS DE MADERA Y/O PIEL',
    '5610200' => 'PRODUCTOS QUIMICOS - TRABAJADORES EN EL PROCESAMIENTO Y FABRICACION DE PRODUCTOS QUIMICOS Y FARMACOQUIMICAS',
    '5710200' => 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - TRABAJADORES EN LA FABRICACION DE PRODUCTOS METALICOS, DE HULE Y PLASTICOS',
    '5720800' => 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - ENSAMBLADORES Y ACABADORES DE PRODUCTOS DE PLASTICO',
    '5720900' => 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - FABRICANTES DE HERRAMIENTAS Y TROQUELES',
    '5721000' => 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - HERREROS Y FORJADORES',
    '5721100' => 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - JOYEROS Y ORFEBRES',
    '5722900' => 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - SOLDADORES Y OXICORTADORES',
    '5730600' => 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - TRABAJADORES EN EL ENSAMBLADO DE VEHICULOS, MOLDEADO, LAMINADO Y MONTAJE DE PIEZAS METALICAS, HULE O PLASTICO',
    '5731100' => 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - SUPERVISORES EN LA FABRICACION Y MONTAJE DE ARTICULOS DEPORTIVOS, DE JUGUETES Y SIMILARES',
    '5810200' => 'PRODUCTOS ELECTRICOS Y ELECTRONICOS - TRABAJADORES EN LA FABRICACION DE PRODUCTOS ELECTRICOS Y ELECTRONICOS',
    '5910400' => 'PRODUCTOS IMPRESOS - TRABAJADORES EN LA ELABORACION DE PRODUCTOS IMPRESOS',
    '6120100' => 'TRANSPORTE FERROVIARIO - CONDUCTORES Y OPERADORES DE TREN SUBTERRANEO Y DE TREN LIGERO',
    '6120200' => 'TRANSPORTE FERROVIARIO - TRABAJADORES DE FERROCARRILES',
    '6220100' => 'TRANSPORTE TERRESTRE - CONDUCTORES DE VEHICULOS DE TRANSPORTE, SERVICIOS DE CARGA Y/O REPARTO',
    '6330100' => 'TRANSPORTE AEREO - COORDINADORES Y SUPERVISORES EN SERVICIOS DE TRANSPORTE AEREO',
    '6330200' => 'TRANSPORTE AEREO - DESPACHADORES DE VUELO Y ESPECIALISTAS EN SERVICIOS AEREOS',
    '6330400' => 'TRANSPORTE AEREO - SUPERVISORES DE SISTEMAS DE COMUNICACION PARA LA AERONAVEGACION',
    '6330500' => 'TRANSPORTE AEREO - PILOTOS DE AVIACION E INSTRUCTORES DE VUELO',
    '6330600' => 'TRANSPORTE AEREO - SOBRECARGOS',
    '6420100' => 'TRANSPORTE MARITIMO Y FLUVIAL - CONDUCTORES DE EMBARCACIONES',
    '6430100' => 'TRANSPORTE MARITIMO Y FLUVIAL - JEFES Y CONTROLADORES DE TRAFICO MARITIMO',
    '6430300' => 'TRANSPORTE MARITIMO Y FLUVIAL - PILOTOS, CAPITANES DE PUERTOS Y OFICIALES DE CUBIERTA',
    '7110200' => 'COMERCIO - DESPACHADORES DE GASOLINERA',
    '7110300' => 'COMERCIO - EMPACADORES DE MERCANCIAS',
    '7110500' => 'COMERCIO - TAQUILLEROS',
    '7110600' => 'COMERCIO - VENDEDORES AMBULANTES',
    '7120100' => 'COMERCIO - CAJEROS REGISTRADORES',
    '7130200' => 'COMERCIO - REPRESENTANTES DE VENTAS POR TELEFONO O POR TELEVISION',
    '7130400' => 'COMERCIO - VENDEDORES ESPECIALIZADOS',
    '7140100' => 'COMERCIO - GERENTES O SUPERVISOR DE ESTABLECIMIENTO COMERCIAL',
    '7140200' => 'COMERCIO - GERENTES O EMPLEADOS DE VENTAS',
    '7210100' => 'ALIMENTACION Y HOSPEDAJE - TRABAJADORES DE SERVICIO DE ALIMENTOS Y BEBIDAS',
    '7230200' => 'ALIMENTACION Y HOSPEDAJE - JEFES DE COCINA, RESTAURANTE Y/O BAR',
    '7240200' => 'ALIMENTACION Y HOSPEDAJE - TRABAJADORES DE SERVICIOS DE ALOJAMIENTO',
    '7330200' => 'TURISMO - COORDINADORES DE OPERACIONES EN AGENCIAS DE VIAJES',
    '7330300' => 'TURISMO - GUIAS DE EXCURSIONES O ECOTURISTICO',
    '7430100' => 'DEPORTE Y ESPARCIMIENTO - ANIMADORES RECREATIVOS',
    '7430200' => 'DEPORTE Y ESPARCIMIENTO - ATLETAS, ENTRENADORES O INSTRUCTORES EN DEPORTE Y RECREACION',
    '7430400' => 'DEPORTE Y ESPARCIMIENTO - OFICIALES, JUECES Y ARBITROS DEPORTIVOS',
    '7530100' => 'SERVICIOS PERSONALES - ESTILISTAS, ESTETICISTAS Y MASAJISTAS',
    '7540100' => 'SERVICIOS PERSONALES - TRBAJADORES DE SERVICIOS FUNERARIOS O CEMENTERIOS',
    '7620100' => 'REPARACION DE ARTICULOS DE USO DOMESTICO Y PERSONAL - CERRAJEROS',
    '7620200' => 'REPARACION DE ARTICULOS DE USO DOMESTICO Y PERSONAL - REPARADORES DE ARTICULOS DE HULE',
    '7630100' => 'REPARACION DE ARTICULOS DE USO DOMESTICO Y PERSONAL - RELOJEROS Y REPARADORES DE RELOJES',
    '7630200' => 'REPARACION DE ARTICULOS DE USO DOMESTICO Y PERSONAL - REPARADORES DE APARATOS ELECTRICOS',
    '7720100' => 'LIMPIEZA - SERVICIOS DE CAMARISTAS Y ASEADORES',
    '7720200' => 'LIMPIEZA - TRABAJADORES DE TINTORERIA Y LAVANDERIA',
    '7720300' => 'LIMPIEZA - FUMIGADORES DE PLAGAS',
    '7810200' => 'SERVICIO POSTAL Y MENSAJERIA - EMPLEADOS DE SERVICIOS DE MENSAJERIA',
    '8120100' => 'BOLSA, BANCA Y SEGUROS - GERENTES O TRABAJADORES DE SERVICIOS Y PRODUCTOS FINANCIEROS',
    '8130500' => 'BOLSA, BANCA Y SEGUROS - VALUADORES',
    '8140100' => 'BOLSA, BANCA Y SEGUROS - AGENTES DE VALORES, PROMOTORES Y CORREDORES DE INVERSION',
    '8210100' => 'ADMINISTRACION - TRABAJADORES DE ARCHIVO, ALMACEN DE INVENTARIOS',
    '8220400' => 'ADMINISTRACION - CAPTURISTA Y OPERADORES DE TELEFONO',
    '8220600' => 'ADMINISTRACION - PAGADORES Y COBRADORES',
    '8230300' => 'ADMINISTRACION - DIRECTORES, GERENTES Y EMPLEADOS DE COMPRAS, FINANZAS, RECURSOS HUMANOS Y SERVICIOS ADMINISTRATIVOS',
    '8240100' => 'ADMINISTRACION - ASISTENTES ADMINISTRATIVOS',
    '8240200' => 'ADMINISTRACION - CONTADORES Y AUDITORES',
    '8240600' => 'ADMINISTRACION - DIRECTORES, GERENTES Y EMPLEADOS DE PRODUCCION',
    '8240700' => 'ADMINISTRACION - DIRECTORES, GERENTES Y EMPLEADOS DE SERVICIOS DE TRANSPORTE',
    '8250100' => 'ADMINISTRACION - CONSULTORES',
    '8250200' => 'ADMINISTRACION - DIRECTORES, GERENTES Y EMPLEADOS DE COMERCIALIZACION',
    '8250800' => 'ADMINISTRACION - DIRECTORES, GERENTES Y EMPELADOS ADMINISTRATIVOS',
    '8340100' => 'SERVICIOS LEGALES - ABOGADOS Y ASESORES LEGALES',
    '8340300' => 'SERVICIOS LEGALES - NOTARIOS Y CORREDORES PUBLICOS',
    '9120700' => 'SERVICIOS MEDICOS - ENFERMERAS Y/O PARAMEDICOS',
    '9130300' => 'SERVICIOS MEDICOS - DIETISTAS Y NUTRIOLOGOS',
    '9131200' => 'SERVICIOS MEDICOS - TECNICOS DE LABORATORIO MEDICO',
    '9140200' => 'SERVICIOS MEDICOS - DIRECTORES DE INSTITUCIONES EN EL CUIDADO DE LA SALUD',
    '9140400' => 'SERVICIOS MEDICOS - FARMACEUTICOS',
    '9140500' => 'SERVICIOS MEDICOS - FISIOTERAPEUTAS Y QUIROPRACTICOS',
    '9140700' => 'SERVICIOS MEDICOS - MEDICOS ESPECIALISTAS',
    '9140800' => 'SERVICIOS MEDICOS - MEDICOS GENERALES Y FAMILIARES',
    '9230100' => 'INSPECCION - INSPECTORES DE SALUD AMBIENTAL, SANIDAD Y DEL TRABAJO',
    '9230200' => 'INSPECCION - INSPECTORES DE TRANSPORTE DE CARGA Y DE PASAJEROS',
    '9230300' => 'INSPECCION - INSPECTORES FISCALES Y DE PRECIOS',
    '9230400' => 'INSPECCION - INSPECTORES SANITARIOS Y DE CONTROL DE CALIDAD DE PRODUCTOS CARNICOS, PESQUEROS Y AGRICOLAS',
    '9330100' => 'SEGURIDAD SOCIAL - CONSEJEROS DE EMPLEO',
    '9330300' => 'SEGURIDAD SOCIAL - TRABAJADORES DE SERVICIO SOCIAL Y DE LA COMUNIDAD',
    '9420100' => 'PROTECCION DE BIENES Y/O PERSONAS - BOMBEROS',
    '9420300' => 'PROTECCION DE BIENES Y/O PERSONAS - GUARDIAS DE SEGURIDAD',
    '9430100' => 'PROTECCION DE BIENES Y/O PERSONAS - DETECTIVES PRIVADOS',
    '1014010' => 'RADIO, CINE, TELEVISION Y TEATRO - DISEÑADORES GRAFICOS',
    '1014030' => 'RADIO, CINE, TELEVISION Y TEATRO - EDITORES, PERIODISTAS, REPORTEROS Y REDACTORES',
    '1023010' => 'RADIO, CINE, TELEVISION Y TEATRO - ASISTENTES Y/U OPERADORES DE PRODUCCION DE CINE, RADIO Y TELEVISION',
    '1023070' => 'RADIO, CINE, TELEVISION Y TEATRO - LOCUTORES, COMENTARISTAS Y CRONISTAS DE RADIO Y TELEVISION',
    '1024020' => 'RADIO, CINE, TELEVISION Y TEATRO - PRODUCTORES Y DIRECTORES DE CINE, TELEVISION Y TEATRO',
    '1033010' => 'INTERPRETACION ARTISTICA - ACTORES, BAILARINES, MUSICOS, ESCRITORES',
    '1033020' => 'INTERPRETACION ARTISTICA - ARTESANOS',
    '1033040' => 'INTERPRETACION ARTISTICA - FOTOGRAFOS',
    '1034010' => 'INTERPRETACION ARTISTICA - ARTISTAS PLASTICOS',
    '1044010' => 'TRADUCCION E INTERPRETACION LINGüISTICA - INTERPRETES Y/O TRADUCTORES',
    '1052010' => 'PUBLICIDAD, PROPAGANDA Y RELACIONES PUBLICAS - MODELOS Y EDECANES',
    '1054010' => 'PUBLICIDAD, PROPAGANDA Y RELACIONES PUBLICAS - DIRECTORES, GERENTES Y EMPLEADOS DE PUBLICIDAD',
    '1112010' => 'INVESTIGACION - ENCUESTADORES Y CODIFICADORES',
    '1113010' => 'INVESTIGACION - ASISTENTES DE INVESTIGADORES',
    '1113020' => 'INVESTIGACION - QUIMICOS Y/O TECNICOS EN QUIMICA',
    '1114010' => 'INVESTIGACION - BIOLOGOS Y CIENTIFICOS RELACIONADOS',
    '1114020' => 'INVESTIGACION - ECONOMISTAS Y POLITOLOGOS (NO FUNCIONARIOS PUBLICOS)',
    '1114030' => 'INVESTIGACION - FISICOS ASTRONOMOS',
    '1114040' => 'INVESTIGACION - GEOLOGOS, GEOQUIMICOS, GEOFISICOS Y GEOGRAFOS',
    '1114050' => 'INVESTIGACION - INVESTIGADORES Y CONSULTORES EN MERCADOTECNIA',
    '1114060' => 'INVESTIGACION - MATEMATICOS, ESTADISTICOS Y ACTUARIOS',
    '1114070' => 'INVESTIGACION - METEOROLOGOS',
    '1114090' => 'INVESTIGACION - SOCIOLOGOS, ANTROPOLOGOS E HISTORIADORES',
    '1123020' => 'ENSEÑANZA - CAPACITADORES E INSTRUCTORES',
    '1124070' => 'ENSEÑANZA - PROFESORES O DOCENTES',
    '1125010' => 'ENSEÑANZA - DIRECTORES GENERALES DE EDUCACION',
    '1133010' => 'DIFUSION CULTURAL - PROMOTORES DE DIFUSION CULTURAL',
    '1134010' => 'DIFUSION CULTURAL - TRABAJADORES DE BIBLIOTECA, ARCHIVO, MUSEO Y GALERIA DE ARTE',
    '1135010' => 'OTRAS OCUPACIONES - ESTUDIANTE O MENOR DE EDAD SIN OCUPACION',
    '1135080' => 'OTRAS OCUPACIONES - PROPIETARIO, ACCIONISTA O SOCIO',
    '1135020' => 'OTRAS OCUPACIONES - DESEMPLEADO',
    '1135030' => 'OTRAS OCUPACIONES - JUBILADO O PENSIONADO',
    '1135050' => 'OTRAS OCUPACIONES - AMA DE CASA O QUEHACERES DEL HOGAR',
    '1135060' => 'OTRAS OCUPACIONES - MINISTROS DE CULTO RELIGIOSO (SACERDOTE, PASTOR, MONJA, ETC)',
    '1135070' => 'OTRAS OCUPACIONES - AGENTE ADUANAL',
    '1136010' => 'SECTOR PUBLICO - EMPLEADO DEL PODER EJECUTIVO FEDERAL',
    '1136020' => 'SECTOR PUBLICO - EMPLEADO PODER EJECUTIVO ESTATAL O DEL DISTRITO FEDERAL',
    '1136030' => 'SECTOR PUBLICO - EMPLEADO DEL PODER EJECUTIVO MUNICIPAL O DELEGACIONAL',
    '1136040' => 'SECTOR PUBLICO - EMPLEADO DEL PODER JUDICIAL FEDERAL',
    '1136070' => 'SECTOR PUBLICO - EMPLEADO DEL PODER JUDICIAL ESTATAL O DEL DISTRITO FEDERAL',
    '1136050' => 'SECTOR PUBLICO - EMPLEADO DEL PODER LEGISLATIVO FEDERAL',
    '1136060' => 'SECTOR PUBLICO - EMPLEADO DEL PODER LEGISLATIVO ESTATAL O DEL DISTRITO FEDERAL',
    '1136090' => 'SECTOR PUBLICO - EJERCITO, ARMADA Y FUERZA AEREA',
    '1136080' => 'ORGANISMOS INTERNACIONALES Y EXTRATERRITORIALES - EMPLEADOS DE ORGANISMOS INTERNACIONALES Y EXTRATERRITORIALES',
];
$CHV_CATALOGOS['giro_mercantil'] = $TSC_CATALOGOS['giro_mercantil'] ?? ($DIN_CATALOGOS['giro_mercantil'] ?? []);

if (!function_exists('chvCatalogoOptions')) {
    function chvCatalogoOptions(string $key, ?string $selected = null, ?callable $labeler = null, bool $withPlaceholder = true): string
    {
        global $CHV_CATALOGOS;
        $items = $CHV_CATALOGOS[$key] ?? [];
        $html = '';
        if ($withPlaceholder) {
            $html .= '<option value="">-- Seleccione --</option>';
        }
        foreach ($items as $k => $v) {
            $label = $labeler ? $labeler((string)$k, (string)$v) : ((string)$k . ' - ' . (string)$v);
            $sel = ((string)$selected === (string)$k) ? ' selected' : '';
            $html .= '<option value="' . htmlspecialchars((string)$k, ENT_QUOTES, 'UTF-8') . '"' . $sel . '>'
                . htmlspecialchars($label, ENT_QUOTES, 'UTF-8')
                . '</option>';
        }
        return $html;
    }
}

if (!function_exists('chvCatalogosJson')) {
    function chvCatalogosJson(): string
    {
        global $CHV_CATALOGOS;
        return json_encode($CHV_CATALOGOS, JSON_UNESCAPED_UNICODE);
    }
}
