<?php
/**
 * Catálogos UIF para DIN (Desarrollo Inmobiliario Nacional)
 * Según Portal de Prevención de Lavado de Dinero — SAT/UIF
 * https://www.sat.gob.mx/consulta/44891/portal-de-prevencion-de-lavado-de-dinero
 */

$DIN_CATALOGOS = [];

/* ═══════════════════════════════════════════
 * 0. ACTIVIDADES VULNERABLES (clave_actividad)
 *    Campo: clave_actividad — clave_actividad_type
 *    Para DIN siempre es "DIN" (readonly en formulario)
 * ═══════════════════════════════════════════ */
$DIN_CATALOGOS['clave_actividad'] = [
    'DIN' => 'Desarrollo inmobiliario (compra/venta de bienes inmuebles por cuenta propia o de clientes)',
];

/* ═══════════════════════════════════════════
 * 1. ENTIDADES FEDERATIVAS (INEGI / UIF)
 *    Campo: entidad_federativa — digito_1-2_type
 * ═══════════════════════════════════════════ */
$DIN_CATALOGOS['entidad_federativa'] = [
    '1'  => 'Aguascalientes',
    '2'  => 'Baja California',
    '3'  => 'Baja California Sur',
    '4'  => 'Campeche',
    '5'  => 'Coahuila de Zaragoza',
    '6'  => 'Colima',
    '7'  => 'Chiapas',
    '8'  => 'Chihuahua',
    '9'  => 'Distrito Federal',
    '10' => 'Durango',
    '11' => 'Guanajuato',
    '12' => 'Guerrero',
    '13' => 'Hidalgo',
    '14' => 'Jalisco',
    '15' => 'México',
    '16' => 'Michoacán de Ocampo',
    '17' => 'Morelos',
    '18' => 'Nayarit',
    '19' => 'Nuevo León',
    '20' => 'Oaxaca',
    '21' => 'Puebla',
    '22' => 'Querétaro',
    '23' => 'Quintana Roo',
    '24' => 'San Luis Potosí',
    '25' => 'Sinaloa',
    '26' => 'Sonora',
    '27' => 'Tabasco',
    '28' => 'Tamaulipas',
    '29' => 'Tlaxcala',
    '30' => 'Veracruz de Ignacio de la Llave',
    '31' => 'Yucatán',
    '32' => 'Zacatecas',
];

/* ═══════════════════════════════════════════
 * 2. TIPO DE ALERTA UIF
 *    Campo: tipo_alerta — digito_3-4_type
 * ═══════════════════════════════════════════ */
$DIN_CATALOGOS['tipo_alerta'] = [
    '100'  => 'El cliente o usuario no presenta ningún comportamiento inusual',
    '3901' => 'El(los) cliente(s) o usuario(s) se resiste(n) a proporcionar datos o documentos que lo(s) identifiquen',
    '3902' => 'El(los) cliente(s) o usuario(s) se niega(n) o evita(n) llenar los formularios o formatos requeridos',
    '3903' => 'El(los) cliente(s) o usuario(s) modifica(n) la operación al momento de ser requerido cualquier dato de identificación en tiempo sin razón aparente',
    '3904' => 'El(los) cliente(s) o usuario(s) presenta(n) documentación con alteraciones, tachaduras, enmendaduras o datos incongruentes, o en el precio y condiciones de la transacción',
    '3905' => 'De acuerdo con medios informativos u otras fuentes de información pública, se tiene conocimiento o sospecha de que el cliente, un familiar o persona relacionada, está vinculado con actividades ilícitas o se encuentra bajo proceso de investigación',
    '3906' => 'La(s) persona(s) que participa(n) en la operación no quiere(n) ser relacionada(s) con el desarrollo del Inmueble',
    '3907' => 'Se detecta participación de personas políticamente expuestas que participa(n) en la operación',
    '3908' => 'No es posible verificar la identidad de quien aporta los recursos',
    '3909' => 'Los recursos son aportados por un tercero sin que exista relación aparente con la operación',
    '3910' => 'El cliente busca realizar la operación a través de un tercero sin justificación',
    '3911' => 'Los montos de las aportaciones son elevados',
    '3912' => 'La documentación presentada es inexistente o de difícil verificación por parte del Sujeto Obligado',
    '3913' => 'La(s) persona(s) que participa(n) en la operación intenta(n) sobornar, extorsionar o amenaza(n) con el fin de realizar la operación fuera de los parámetros establecidos, o con la finalidad de evitar el envío del Aviso',
    '9999' => 'Otro (especificar en descripción de alerta)',
];

/* ═══════════════════════════════════════════
 * 3. TIPO DE OPERACIÓN UIF — DIN (Fracción V/V Bis)
 *    Campo: tipo_operacion — digito_3-4_type
 * ═══════════════════════════════════════════ */
$DIN_CATALOGOS['tipo_operacion'] = [
    '1601' => 'Aportación a desarrollo(s) inmobiliario(s)',
];

/* ═══════════════════════════════════════════
 * 4. TIPO DE DESARROLLO INMOBILIARIO UIF
 *    Campo: tipo_desarrollo — digito_1-2_type
 * ═══════════════════════════════════════════ */
$DIN_CATALOGOS['tipo_desarrollo'] = [
    '1'  => 'Habitacional',
    '2'  => 'Comercial',
    '3'  => 'Oficinas',
    '4'  => 'Industrial',
    '5'  => 'Mixto (Habitacional y Comercial)',
    '99' => 'Otro',
];

/* ═══════════════════════════════════════════
 * 5. INSTRUMENTO MONETARIO UIF
 *    Campo: instrumento_monetario — digito_1-2_type
 * ═══════════════════════════════════════════ */
$DIN_CATALOGOS['instrumento_monetario'] = [
    '1'  => 'Efectivo',
    '2'  => 'Tarjeta de Crédito',
    '3'  => 'Tarjeta de Debito',
    '4'  => 'Tarjeta de Prepago',
    '5'  => 'Cheque Nominativo',
    '6'  => 'Cheque de Caja',
    '7'  => 'Cheques de Viajero',
    '8'  => 'Transferencia Interbancaria',
    '9'  => 'Transferencia Misma Institución',
    '10' => 'Transferencia Internacional',
    '11' => 'Orden de Pago',
    '12' => 'Giro',
    '13' => 'Oro o Platino Amonedados',
    '14' => 'Plata Amonedada',
    '15' => 'Metales Preciosos',
];

/* ═══════════════════════════════════════════
 * 6. MONEDA / DIVISA UIF (clave numérica)
 *    Campo: moneda — digito_1-3_type
 * ═══════════════════════════════════════════ */
$DIN_CATALOGOS['moneda'] = [
    '1'   => 'Afgani - AFN - Afganistán',
    '2'   => 'Baht - THB - Tailandia',
    '3'   => 'Balboa - PAB - Panamá',
    '4'   => 'Birr Etíope - ETB - Etiopía',
    '5'   => 'Bolívar - VES - Venezuela',
    '6'   => 'Boliviano - BOB - Bolivia',
    '7'   => 'Cedi - GHS - Ghana',
    '8'   => 'Colón Costarricense - CRC - Costa Rica',
    '9'   => 'Colón Salvadoreño - SVC - El Salvador',
    '10'  => 'Corona Checa - CZK - República Checa',
    '11'  => 'Corona Danesa - DKK - Dinamarca',
    '12'  => 'Corona Estonia - EEK - Estonia',
    '13'  => 'Corona Islandesa - ISK - Islandia',
    '14'  => 'Corona Noruega - NOK - Noruega',
    '15'  => 'Corona Sueca - SEK - Suecia',
    '16'  => 'Dalasi - GMD - Gambia',
    '17'  => 'Denar - MKD - Macedonia',
    '18'  => 'Dinar Argelino - DZD - Argelia',
    '19'  => 'Dinar Bahriní - BHD - Bahréin',
    '20'  => 'Dinar Iraquí - IQD - Irak',
    '21'  => 'Dinar Jordano - JOD - Jordania',
    '22'  => 'Dinar Kuwaití - KWD - Kuwait',
    '23'  => 'Dinar Libio - LYD - Libia',
    '24'  => 'Dinar Serbio - RSD - Serbia',
    '25'  => 'Dinar Tunecino - TND - Túnez',
    '26'  => 'Dirham de EAU - AED - Emiratos Árabes Unidos',
    '27'  => 'Dirham Marroquí - MAD - Marruecos',
    '28'  => 'Dobra - STD - Santo Tomé y Príncipe',
    '29'  => 'Dólar Australiano - AUD - Australia',
    '30'  => 'Dólar de Bahamas - BSD - Bahamas',
    '31'  => 'Dólar de Barbados - BBD - Barbados',
    '32'  => 'Dólar de Belice - BZD - Belice',
    '33'  => 'Dólar de Bermuda - BMD - Bermuda',
    '34'  => 'Dólar de Brunéi - BND - Brunéi',
    '35'  => 'Dólar de Islas Caimán - KYD - Islas Caimán',
    '36'  => 'Dólar de Fiji - FJD - Fiji',
    '37'  => 'Dólar de Guyana - GYD - Guyana',
    '38'  => 'Dólar de Hong Kong - HKD - Hong Kong',
    '39'  => 'Dólar de Islas Salomón - SBD - Islas Salomón',
    '40'  => 'Dólar de Jamaica - JMD - Jamaica',
    '41'  => 'Dólar de Namibia - NAD - Namibia',
    '42'  => 'Dólar de Nueva Zelanda - NZD - Nueva Zelanda',
    '43'  => 'Dólar de Singapur - SGD - Singapur',
    '44'  => 'Dólar de Surinam - SRD - Surinam',
    '45'  => 'Dólar de Trinidad y Tobago - TTD - Trinidad y Tobago',
    '46'  => 'Dólar del Caribe Oriental - XCD - Caribe Oriental',
    '47'  => 'Dólar Estadounidense - USD - Estados Unidos',
    '48'  => 'Dólar Canadiense - CAD - Canadá',
    '49'  => 'Dólar de Taiwán - TWD - Taiwán',
    '50'  => 'Dólar Liberiano - LRD - Liberia',
    '51'  => 'Dólar Zimbabuense - ZWL - Zimbabwe',
    '52'  => 'Dong - VND - Vietnam',
    '53'  => 'Dram Armenio - AMD - Armenia',
    '54'  => 'Escudo Caboverdiano - CVE - Cabo Verde',
    '55'  => 'Euro - EUR - Unión Europea',
    '56'  => 'Florín Arubeño - AWG - Aruba',
    '57'  => 'Florín de Antillas Neerlandesas - ANG - Antillas Neerlandesas',
    '58'  => 'Forint - HUF - Hungría',
    '59'  => 'Franco Burundés - BIF - Burundi',
    '60'  => 'Franco CFA BCEAO - XOF - África Occidental',
    '61'  => 'Franco CFA BEAC - XAF - África Central',
    '62'  => 'Franco Comorense - KMF - Comoras',
    '63'  => 'Franco Congoleño - CDF - Congo',
    '64'  => 'Franco de Yibuti - DJF - Yibuti',
    '65'  => 'Franco Guineano - GNF - Guinea',
    '66'  => 'Franco Ruandés - RWF - Ruanda',
    '67'  => 'Franco Suizo - CHF - Suiza',
    '68'  => 'Franco CFP - XPF - Polinesia Francesa',
    '69'  => 'Gourde - HTG - Haití',
    '70'  => 'Guaraní - PYG - Paraguay',
    '71'  => 'Hryvnia - UAH - Ucrania',
    '72'  => 'Kina - PGK - Papúa Nueva Guinea',
    '73'  => 'Kip - LAK - Laos',
    '74'  => 'Kuna - HRK - Croacia',
    '75'  => 'Kwacha Malauiano - MWK - Malaui',
    '76'  => 'Kwacha Zambiano - ZMW - Zambia',
    '77'  => 'Kwanza - AOA - Angola',
    '78'  => 'Kyat - MMK - Myanmar',
    '79'  => 'Lari - GEL - Georgia',
    '80'  => 'Lek - ALL - Albania',
    '81'  => 'Lempira - HNL - Honduras',
    '82'  => 'Leone - SLL - Sierra Leona',
    '83'  => 'Leu Moldavo - MDL - Moldavia',
    '84'  => 'Leu Rumano - RON - Rumania',
    '85'  => 'Lev Búlgaro - BGN - Bulgaria',
    '86'  => 'Libra Egipcia - EGP - Egipto',
    '87'  => 'Libra Esterlina - GBP - Reino Unido',
    '88'  => 'Libra Libanesa - LBP - Líbano',
    '89'  => 'Libra Siria - SYP - Siria',
    '90'  => 'Lilangeni - SZL - Suazilandia',
    '91'  => 'Lira Turca - TRY - Turquía',
    '92'  => 'Litas Lituano - LTL - Lituania',
    '93'  => 'Loti - LSL - Lesoto',
    '94'  => 'Manat Azerbaiyano - AZN - Azerbaiyán',
    '95'  => 'Manat Turcomano - TMT - Turkmenistán',
    '96'  => 'Marco Convertible - BAM - Bosnia y Herzegovina',
    '97'  => 'Metical - MZN - Mozambique',
    '98'  => 'Naira - NGN - Nigeria',
    '99'  => 'Nakfa - ERN - Eritrea',
    '100' => 'Ngultrum - BTN - Bután',
    '101' => 'Nuevo Sol - PEN - Perú',
    '102' => 'Ouguiya - MRO - Mauritania',
    '103' => 'Pa\'anga - TOP - Tonga',
    '104' => 'Pataca - MOP - Macao',
    '105' => 'Peso Argentino - ARS - Argentina',
    '106' => 'Peso Chileno - CLP - Chile',
    '107' => 'Peso Colombiano - COP - Colombia',
    '108' => 'Peso Cubano Convertible - CUC - Cuba',
    '109' => 'Peso Cubano - CUP - Cuba',
    '110' => 'Peso Dominicano - DOP - República Dominicana',
    '111' => 'Peso Filipino - PHP - Filipinas',
    '112' => 'Peso Mexicano - MXN - México',
    '113' => 'Peso Uruguayo - UYU - Uruguay',
    '114' => 'Pula - BWP - Botsuana',
    '115' => 'Quetzal - GTQ - Guatemala',
    '116' => 'Rand - ZAR - Sudáfrica',
    '117' => 'Real Brasileño - BRL - Brasil',
    '118' => 'Rial de Catar - QAR - Catar',
    '119' => 'Rial Iraní - IRR - Irán',
    '120' => 'Rial Omaní - OMR - Omán',
    '121' => 'Rial Saudí - SAR - Arabia Saudita',
    '122' => 'Rial Yemení - YER - Yemen',
    '123' => 'Riel - KHR - Camboya',
    '124' => 'Ringgit - MYR - Malasia',
    '125' => 'Rublo Bielorruso - BYR - Bielorrusia',
    '126' => 'Rublo Ruso - RUB - Rusia',
    '127' => 'Rupia de Mauricio - MUR - Mauricio',
    '128' => 'Rupia de Seychelles - SCR - Seychelles',
    '129' => 'Rupia de Sri Lanka - LKR - Sri Lanka',
    '130' => 'Rupia India - INR - India',
    '131' => 'Rupia Indonesa - IDR - Indonesia',
    '132' => 'Rupia Nepalesa - NPR - Nepal',
    '133' => 'Rupia Pakistaní - PKR - Pakistán',
    '134' => 'Rufiyaa - MVR - Maldivas',
    '135' => 'Shekel - ILS - Israel',
    '136' => 'Som - KGS - Kirguistán',
    '137' => 'Somoni - TJS - Tayikistán',
    '138' => 'Sum Uzbeko - UZS - Uzbekistán',
    '139' => 'Taka - BDT - Bangladesh',
    '140' => 'Tala - WST - Samoa',
    '141' => 'Tenge - KZT - Kazajistán',
    '142' => 'Tugrik - MNT - Mongolia',
    '143' => 'Vatu - VUV - Vanuatu',
    '144' => 'Won Norcoreano - KPW - Corea del Norte',
    '145' => 'Won Surcoreano - KRW - Corea del Sur',
    '146' => 'Yen - JPY - Japón',
    '147' => 'Yuan Renminbi - CNY - China',
    '148' => 'Zloty - PLN - Polonia',
    '149' => 'Córdoba Oro - NIO - Nicaragua',
    '150' => 'Chelín Keniano - KES - Kenia',
    '151' => 'Chelín Somalí - SOS - Somalia',
    '152' => 'Chelín Tanzano - TZS - Tanzania',
    '153' => 'Chelín Ugandés - UGX - Uganda',
    '154' => 'Centenario de Oro - XAU - México',
    '155' => 'Onza de Plata - XAG - México',
    '156' => '2 Aztecas de Oro - MXD - Mexico',
    '157' => '1/2 Hidalgo de Oro - MXC - Mexico',
    '158' => '1/4 Hidalgo de Oro - MXO - Mexico',
    '159' => 'Centenario de Oro - MXA - Mexico',
    '160' => '2 Azteca de Oro - MXD - Mexico',
    '161' => '1/2 Hidalgo de Oro - MXC - Mexico',
    '162' => '1/4 Hidalgo de Oro - MXO - Mexico',
    '163' => '1/4 Hidalgo de Oro - MXE - Mexico',
    '164' => '1/5 Hidalgo de Oro - MXG - Mexico',
    '165' => '1 Oz Libertad de Oro - MXH - Mexico',
    '166' => '1/2 Oz Libertad de Oro - MXI - Mexico',
    '167' => '1/4 Oz Libertad de Oro - MXJ - Mexico',
    '168' => '1/10 Oz Libertad de Oro - MXI - Mexico',
    '169' => '1/20 Oz Libertad de Oro - MXK - Mexico',
    '170' => '1 Oz Libertad de Plata - MXL - Mexico',
    '171' => '1/2 Oz Libertad de Plata - MXM - Mexico',
    '172' => '1/4 Oz Libertad de Plata - MXN - Mexico',
    '173' => '1/10 Oz Libertad de Plata - MXO - Mexico',
    '174' => '1/20 Oz Libertad de Plata - MXP - Mexico',
    '175' => 'Onza de Plata - XAG - N/A',
    '176' => 'Onza de Oro - XAU - N/A',
    '177' => 'Franco de Oro (Special settlement currency) - XFO - N/A',
    '178' => 'Onza de Paladio - XPD - N/A',
    '179' => 'Onza de Platino - XPT - N/A',
    '180' => 'Franco CFA de Africa Central - XAF - N/A',
    '181' => 'Dolar del Caribe Oriental - XCD - N/A',
    '182' => 'Franco UIC (Special settlement currency) - XFU - N/A',
    '183' => 'Franco CFA de Africa Occidental - XOF - N/A',
    '184' => 'Franco CFP - XPF - N/A',
];

/* ═══════════════════════════════════════════
 * 7. TIPO DE TERCERO UIF
 *    Campo: tipo_tercero — digito_1-2_type
 * ═══════════════════════════════════════════ */
$DIN_CATALOGOS['tipo_tercero'] = [
    '1'  => 'Proveedores',
    '2'  => 'Cliente(s) en Preventa',
    '99' => 'Otro',
];

/* ═══════════════════════════════════════════
 * 8. TIPO DE INSTITUCIÓN FINANCIERA UIF
 *    Campo: tipo_institucion — digito_1-2_type
 * ═══════════════════════════════════════════ */
$DIN_CATALOGOS['tipo_institucion'] = [
    '04' => 'ADMINISTRADORAS DE FONDOS PARA EL RETIRO',
    '07' => 'ALMACENES GENERALES DE DEPOSITO',
    '10' => 'ARRENDADORAS FINANCIERAS',
    '13' => 'CASAS DE BOLSA',
    '16' => 'CASAS DE CAMBIO',
    '18' => 'SECTOR ENERGIA',
    '19' => 'EMPRESAS DE FACTORAJE FINANCIERO',
    '22' => 'INSTITUCIONES DE SEGUROS',
    '25' => 'EMPRESAS DE SERVICIOS A INTERMEDIARIOS BURSATILES',
    '27' => 'SOCIEDADES FINANCIERAS POPULARES',
    '28' => 'SERVICIOS COMPLEMENTARIOS',
    '29' => 'ENTIDADES DE AHORRO Y CREDITO POPULAR',
    '30' => 'ORGANISMOS DE INTEGRACION',
    '31' => 'FONDOS Y FIDEICOMISOS DE FOMENTO ECONOMICO',
    '32' => 'ORGANISMOS DE SERVICIO SOCIAL',
    '34' => 'INMOBILIARIAS',
    '37' => 'BANCA DE DESARROLLO',
    '40' => 'BANCA MULTIPLE',
    '43' => 'INSTITUCIONES DE FIANZAS',
    '46' => 'OFICINAS DE REPRESENTACION DE INTERMEDIARIOS FINANCIEROS DEL EXTERIOR',
    '47' => 'OFICINAS DE REPRESENTACION DE CASAS DE BOLSA DEL EXTERIOR EN MEXICO',
    '50' => 'FINANCIERA RURAL',
    '52' => 'SOCIEDADES DE INVERSION',
    '55' => 'SOCIEDADES CONTROLADORAS',
    '58' => 'SOCIEDADES DE AHORRO Y PRESTAMO',
    '61' => 'SOCIEDADES DE INFORMACION CREDITICIA',
    '64' => 'SOCIEDADES DE INVERSION ESPECIALIZADAS DE FONDOS PARA EL RETIRO',
    '67' => 'SOCIEDADES FINANCIERAS DE OBJETO LIMITADO',
    '68' => 'SOCIEDADES FINANCIERAS DE OBJETO MULTIPLE',
    '69' => 'SOCIEDADES FINANCIERAS DE OBJETO MULTIPLE (ENTIDADES NO REGULADAS)',
    '70' => 'SOCIEDADES OPERADORAS DE SOCIEDADES DE INVERSION',
    '71' => 'SOCIEDADES DISTRIBUIDORAS DE ACCIONES DE SOCIEDADES DE INVERSION',
    '72' => 'VALUADORAS DE ACCIONES DE SOCIEDADES DE INVERSION',
    '76' => 'OPERADORES',
    '79' => 'SUCURSALES EN EL EXTRANJERO',
    '85' => 'UNIONES DE CREDITO',
    '88' => 'TRANSMISORES DE DINERO',
    '89' => 'CENTROS CAMBIARIOS',
    '90' => 'ASESORES EN INVERSIONES',
    '99' => 'OTROS ORGANISMOS NO FINANCIEROS',
];

/* ═══════════════════════════════════════════
 * 9. TIPO DE CRÉDITO UIF
 *    Campo: tipo_credito — digito_1-2_type
 * ═══════════════════════════════════════════ */
$DIN_CATALOGOS['tipo_credito'] = [
    '1' => 'Crédito Corporativo',
    '2' => 'Crédito Puente',
    '3' => 'Crédito Hipotecario',
];

/* ═══════════════════════════════════════════
 * 10. PRIORIDAD
 *     Campo: prioridad — prioridad_type
 * ═══════════════════════════════════════════ */
$DIN_CATALOGOS['prioridad'] = [
    '1' => 'Normal',
    '2' => 'Prioritario (24 horas)',
];

/* ═══════════════════════════════════════════
 * 11. GIRO MERCANTIL (persona_moral)
 *     Campo: giro_mercantil — texto_7_type
 * ═══════════════════════════════════════════ */
$DIN_CATALOGOS['giro_mercantil'] = [
    '0000000' => 'NO APLICA',
    '1110001' => 'SECTOR PRIMARIO - AGRICULTURA',
    '1120001' => 'SECTOR PRIMARIO - GANADERIA',
    '1130001' => 'SECTOR PRIMARIO - SILVICULTURA',
    '1140001' => 'SECTOR PRIMARIO - PESCA',
    '1150001' => 'SECTOR PRIMARIO - EXPLOTACION DE OTROS ANIMALES (AVICULTURA, APICULTURA, ETC)',
    '1160001' => 'SECTOR PRIMARIO - CAZA Y CAPTURA',
    '2110001' => 'MINERIA - CARBON Y DERIVADOS',
    '2120001' => 'MINERIA - ACTIVIDADES RELACIONADAS CON EL PETROLEO Y EL GAS',
    '2130001' => 'MINERIA - MINERALES METALICOS',
    '2140001' => 'MINERIA - PLATA',
    '2150001' => 'MINERIA - ORO',
    '2510001' => 'ELECTRICIDAD - GENERACION Y TRANSMISION DE ENERGIA ELECTRICA, SUMINISTRO DE AGUA Y DE GAS',
    '2710001' => 'CONSTRUCCION - OTRAS ACTIVIDADES RELACIONADAS CON LA CONSTRUCCION',
    '2720001' => 'CONSTRUCCION - OBRAS DE INGENIERIA CIVIL',
    '2730001' => 'CONSTRUCCION - EDIFICACION',
    '2740001' => 'CONSTRUCCION - SERVICIOS DE ACABADO EN EDIFICACIONES',
    '2750001' => 'CONSTRUCCION - SERVICIOS DE BLINDAJE VEHICULAR O TOTAL EN INMUEBLES',
    '3110001' => 'INDUSTRIA - ALIMENTOS',
    '3120001' => 'INDUSTRIA - BEBIDAS Y DEL TABACO',
    '3130001' => 'INDUSTRIA - PRENDAS DE VESTIR',
    '3140001' => 'INDUSTRIA - TEXTIL',
    '3150001' => 'INDUSTRIA - MADERA',
    '3210001' => 'INDUSTRIA - IMPRENTA E INDUSTRIAS CONEXAS',
    '3220001' => 'INDUSTRIA - PAPEL',
    '3230001' => 'INDUSTRIA - PRODUCTOS DERIVADOS DEL PETROLEO Y DEL CARBON',
    '3240001' => 'INDUSTRIA - QUIMICA',
    '3250001' => 'INDUSTRIA - PLASTICO Y DEL HULE',
    '3260001' => 'INDUSTRIA - PRODUCTOS A BASE DE MINERALES NO METALICOS (VIDRIO, LOZA, CEMENTO)',
    '3270001' => 'INDUSTRIA - METALICA BASICA',
    '3280001' => 'INDUSTRIA - PRODUCTOS METALICOS (HERRAMIENTA, ESTRUCTURAS, PIEZAS)',
    '3290001' => 'INDUSTRIA - ACCESORIOS, APARATOS ELECTRICOS Y EQUIPO DE GENERACION DE ENERGIA ELECTRICA',
    '3310001' => 'INDUSTRIA - EQUIPO DE TRANSPORTE',
    '3330001' => 'INDUSTRIA - MAQUINARIA Y EQUIPO',
    '3350001' => 'INDUSTRIA - MUEBLES, COLCHONES Y PERSIANAS',
    '3410001' => 'INDUSTRIA - OTRAS INDUSTRIAS MANUFACTURERAS',
    '3420001' => 'INDUSTRIA - DERIVADOS Y COQUE DE METALES Y PIEDRAS PRECIOSAS',
    '3430001' => 'COMERCIO - CALZADO, MALETAS Y PRENDAS DE VESTIR',
    '3440001' => 'COMERCIO - ARTICULOS Y ACCESORIOS PARA EL COMPUTO, ELECTRODOMESTICOS Y APARATOS DE LINEA BLANCA',
    '3450001' => 'COMERCIO - MATERIAS PRIMAS AGROPECUARIAS Y FORESTALES PARA LA INDUSTRIA, Y MATERIALES DE DESECHO',
    '3460001' => 'COMERCIO - MAQUINARIA, EQUIPO DE COMPUTO Y MOBILIARIO DE OFICINA EN GENERAL',
    '4610001' => 'COMERCIO - PRODUCTOS FARMACEUTICOS',
    '4620001' => 'COMERCIO - ARTICULOS DE PERFUMERIA, ACCESORIOS DE VESTIR Y CALZADO',
    '4630001' => 'COMERCIO - ARTICULOS DE PAPELERIA',
    '4650001' => 'COMERCIO - AUTOPARTES',
    '4660001' => 'COMERCIO - ABARROTES',
    '4670001' => 'COMERCIO - OPT.CLUB DE IMPRESION',
    '4680001' => 'COMERCIO - ARTICULOS PARA LA LIMPIEZA',
    '4690001' => 'COMERCIO - ARTICULOS DE FERRETERIA E INSTRUMENTOS DE MEDICION',
    '4710001' => 'COMERCIO - ARREGLOS Y REPARACIONES PARA EL INTERIOR',
    '4720001' => 'COMERCIO - ARTICULOS DE CRISTALERIA, BLANQUERIA Y VIDRIOS',
    '4730001' => 'COMERCIO - CIGARROS, PUROS Y TABACO',
    '4740001' => 'COMERCIO - VEHICULOS Y SUS REFACCIONES',
    '4750001' => 'COMERCIO - COMBUSTIBLES (GASOLINERAS)',
    '4760001' => 'COMERCIO - CURIOSIDADES, ARTICULOS DE LIBRERIA Y ANTIGÜEDADES',
    '4770001' => 'COMERCIO - DISCOS, JUGUETES Y BICICLETAS',
    '4780001' => 'COMERCIO - INSTRUMENTOS MUSICALES',
    '4790001' => 'COMERCIO - MASCOTAS Y SUS ACCESORIOS',
    '4810007' => 'COMERCIO - RELOJES, JOYERIA Y ORFEBRERIA',
    '4820001' => 'COMERCIO - ARTICULOS DEPORTIVOS',
    '4830001' => 'COMERCIO - OBRAS DE ARTE',
    '4850001' => 'TRANSPORTE - AEREO',
    '4860001' => 'TRANSPORTE - MARITIMO',
    '4870001' => 'TRANSPORTE - FERROVIARIO',
    '4880001' => 'TRANSPORTE - TERRESTRE',
    '4890007' => 'TRANSPORTE - SERVICIOS RELACIONADOS CON EL TRANSPORTE',
    '4900001' => 'TRANSPORTE - SERVICIOS DE GENCIAS ADUANALES',
    '4910001' => 'TRANSPORTE - ALMACENAMIENTO Y REFRIGERACION',
    '4920001' => 'TRANSPORTE - SERVICIO DE MUDANZAS',
    '5010001' => 'SERVICIOS POSTALES',
    '5020001' => 'SERVICIOS DE ALMACENAMIENTO',
    '5110001' => 'PROCESAMIENTO ELECTRONICO DE INFORMACION Y OTROS SERVICIOS WEB',
    '5120001' => 'SECTOR DE MEDIOS MASIVOS',
    '5210011' => 'SECTOR FINANCIERO - BANCA MULTIPLE',
    '5210021' => 'SECTOR FINANCIERO - BANCA DE DESARROLLO',
    '5220011' => 'SECTOR FINANCIERO - FONDOS Y FIDEICOMISOS FINANCIEROS',
    '5230011' => 'SECTOR FINANCIERO - CASAS DE BOLSA',
    '5240011' => 'SECTOR FINANCIERO - OTRAS DE INTERMEDIACION CREDITICIA Y FINANCIERA NO DUPLICA (ARRENDADORA Y PROVEEDOR DE TARJETA DE CREDITO NO BANCARIA, FINANCIAMIENTO DE DEUDA PUBLICA, SOCIEDADES FINANCIERAS DE OBJETO LIMITADO)',
    '5250011' => 'SECTOR FINANCIERO - COMPAÑIAS DE SEGUROS',
    '5260011' => 'SECTOR FINANCIERO - COMPAÑIAS DE FIANZAS',
    '5270011' => 'SECTOR FINANCIERO - CASAS DE CAMBIO',
    '5280011' => 'SECTOR FINANCIERO - SOCIEDADES DE INVERSION',
    '5290011' => 'SECTOR FINANCIERO - SOCIEDADES COOPERATIVAS DE AHORRO Y PRESTAMO',
    '5310021' => 'SECTOR FINANCIERO - OTROS SERVICIOS RELACIONADOS CON LA INTERMEDIACION BURSATIL',
    '5320021' => 'SECTOR FINANCIERO - COMPAÑIAS DE FIANZAS',
    '5330021' => 'SECTOR FINANCIERO - ADMINISTRADORAS DE FONDOS PARA EL RETIRO',
    '5340021' => 'SECTOR FINANCIERO - ALMACENES GENERALES DE DEPOSITO',
    '5350021' => 'SECTOR FINANCIERO - AFIANZADORAS',
    '5410011' => 'OTRAS ENTIDADES DE INTERMEDIACION O SECTOR FINANCIERO',
    '9510011' => 'SECTOR INMOBILIARIO E INMUEBLES - ALQUILER SIN INTERMEDIACION DE BIENES RAICES',
    '9520011' => 'SECTOR INMOBILIARIO E INMUEBLES - INMOBILIARIAS Y CORREDORES DE BIENES RAICES',
    '9530011' => 'SECTOR INMOBILIARIO E INMUEBLES - SERVICIOS RELACIONADOS CON LOS SERVICIOS INMOBILIARIOS',
    '9540011' => 'SECTOR INMOBILIARIO Y DE ALQUILER - ALQUILER DE VEHICULOS',
    '9550011' => 'SECTOR INMOBILIARIO Y DE ALQUILER - SERVICIOS DE ALQUILER DE MARCAS REGISTRADAS, PATENTES Y FRANQUICIAS',
    '9610011' => 'SECTOR DE SERVICIOS PROFESIONALES Y TECNICOS - NOTARIAS',
    '9620011' => 'SECTOR DE SERVICIOS PROFESIONALES Y TECNICOS - DESPACHOS JURIDICOS',
    '9630011' => 'SECTOR DE SERVICIOS PROFESIONALES Y TECNICOS - SERVICIOS CONTABLES Y ACTIVIDADES RELACIONADAS',
    '9640011' => 'SECTOR DE SERVICIOS PROFESIONALES Y TECNICOS - DISEÑO DE SISTEMAS DE COMPUTO Y SERVICIOS RELACIONADOS',
    '9650011' => 'SECTOR DE SERVICIOS PROFESIONALES Y TECNICOS - OTROS SERVICIOS DE CONSULTORIA',
    '9660011' => 'SECTOR DE SERVICIOS PROFESIONALES Y TECNICOS - OTROS SERVICIOS PROFESIONALES Y TECNICOS',
    '9670011' => 'SECTOR DE APOYO A NEGOCIOS - SERVICIOS DE LIMPIEZA E INTERMEDIACION',
    '9680011' => 'SECTOR DE APOYO A NEGOCIOS - SERVICIOS DE ADMINISTRACION DE NEGOCIOS',
    '9690011' => 'SECTOR DE APOYO A NEGOCIOS - AGENCIAS DE VIAJES',
    '9700011' => 'SECTOR DE APOYO A NEGOCIOS - SERVICIOS COMBINADOS DE APOYO EN INSTALACIONES',
    '9710011' => 'SECTOR DE APOYO A NEGOCIOS - SERVICIOS DE PERSONAL EVENTUAL O SERVICIOS DE MANEJO DE RESIDUOS',
    '9720011' => 'SECTOR EDUCATIVO',
    '9730011' => 'SECTOR DE ESPARCIMIENTO - MUSEOS, SITIOS HISTORICOS, JARDINES BOTANICOS Y SIMILARES',
    '9740011' => 'SECTOR DE ESPARCIMIENTO - JUEGOS Y APUESTAS',
    '9750011' => 'SECTOR DE ESPARCIMIENTO - OTROS SERVICIOS',
    '9760011' => 'SECTOR DE ALOJAMIENTO Y RESTAURANTES - HOTELES, MOTELES, SERVICIOS Y AUTOHOTELES',
    '9770011' => 'SECTOR DE ALOJAMIENTO Y RESTAURANTES - RESTAURANTES',
    '9780011' => 'SECTOR DE SERVICIOS - OTROS SERVICIOS',
    '8010021' => 'SECTOR DE SERVICIOS PERSONALES - LAVANDERIAS, SERVICIOS FUNERARIOS, ESTACIONAMIENTOS, REVELADO E IMPRESION DE FOTOGRAFIAS',
    '8020021' => 'ASOCIACIONES Y ORGANIZACIONES - ORGANIZACIONES Y CLUBES DEPORTIVOS, CONDOMINIOS Y RESTAURANTES, SERVICIOS PRIVADOS',
    '8030021' => 'ASOCIACIONES Y ORGANIZACIONES - ORGANIZACIONES DE PORTAFOLIOS',
    '8040021' => 'ASOCIACIONES Y ORGANIZACIONES - ORGANIZACIONES RELIGIOSAS',
    '8050021' => 'ASOCIACIONES Y ORGANIZACIONES - ORGANIZACIONES CIVILES',
    '8110021' => 'ASOCIACIONES Y ORGANIZACIONES - EXTRANJERAS',
    '8120021' => 'ASOCIACIONES Y ORGANIZACIONES - PARTIDOS POLITICOS',
    '9810021' => 'SECTOR PUBLICO - PODER EJECUTIVO FEDERAL',
    '9820021' => 'SECTOR PUBLICO - PODER EJECUTIVO ESTATAL',
    '9830021' => 'SECTOR PUBLICO - PODER EJECUTIVO MUNICIPAL',
    '9840021' => 'SECTOR PUBLICO - PODER JUDICIAL FEDERAL Y DEL DISTRITO FEDERAL',
    '9850021' => 'SECTOR PUBLICO - PODER LEGISLATIVO FEDERAL',
    '9860021' => 'SECTOR PUBLICO - PODER LEGISLATIVO ESTATAL Y DEL DISTRITO FEDERAL',
];

/* ═══════════════════════════════════════════
 * 12. ACTIVIDAD ECONÓMICA (persona_fisica)
 *     Campo: actividad_economica — texto_7_type
 * ═══════════════════════════════════════════ */
$DIN_CATALOGOS['actividad_economica'] = [
    '1000000' => 'NO APLICA',
    '1110100' => 'AGRICULTURA Y SILVICULTURA - ADMINISTRADORES O TRABAJADORES AGRICOLAS',
    '1110400' => 'AGRICULTURA Y SILVICULTURA - ADMINISTRADORES O TRABAJADORES SILVICOLAS Y FORESTALES',
    '1220100' => 'GANADERIA - APICULTORES',
    '1220200' => 'GANADERIA - ADMINISTRADORES, CRIADORES O SUPERVISORES AVICOLAS Y GANADEROS',
    '1330200' => 'PESCA Y ACUACULTURA - PESCADORES Y TRABAJADORES EN LA CRIA Y CULTIVO DE ESPECIES MARINAS',
    '2130100' => 'MINERIA, EXTRACCION Y SUMINISTRO - TECNICOS GEOLOGICOS Y DE MINERALES',
    '2140100' => 'MINERIA, EXTRACCION Y SUMINISTRO - INGENIEROS, OPERADORES O AYUDANTES EN LA EXTRACCION Y REFINACION MINERA',
    '2210100' => 'MINERIA, EXTRACCION Y SUMINISTRO - AYUDANTES EN LA PERFORACION DE POZOS DE PETROLEO Y GAS NATURAL',
    '2240200' => 'MINERIA, EXTRACCION Y SUMINISTRO - INGENIEROS PETROLEROS',
    '2420100' => 'MINERIA, EXTRACCION Y SUMINISTRO - OPERADORES DE CENTRALES O SISTEMAS DE ENERGIA ELECTRICAS',
    '2420200' => 'MINERIA, EXTRACCION Y SUMINISTRO - OPERADORES DE MAQUINAS DE VAPOR',
    '2530100' => 'MINERIA, EXTRACCION Y SUMINISTRO - GERENTE, SUPERVISOR U OPERADORES DE TRATAMIENTO Y POTABILIZACION, ABASTECIMIENTO Y RECOLECCION DE AGUA',
    '3130100' => 'CONSTRUCCION - DECORADORES DE INTERIORES',
    '3130300' => 'CONSTRUCCION - INGENIEROS, TECNICOS Y OPERADORES DE LA CONSTRUCCION',
    '3310300' => 'CONSTRUCCION - COLOCADORES DE PRODUCTOS PREFABRICADOS EN INMUEBLES',
    '3310400' => 'CONSTRUCCION - PINTORES',
    '3310600' => 'CONSTRUCCION - VIDRIEROS',
    '3410200' => 'CONSTRUCCION - REPARADORES DE VIAS DE COMUNICACION',
    '3420100' => 'CONSTRUCCION - PLOMEROS E INSTALADORES DE TUBERIA',
    '3420200' => 'CONSTRUCCION - ARQUITECTOS',
    '4130300' => 'MECANICA - MECANICOS DE EQUIPO PESADO',
    '4130500' => 'MECANICA - INGENIERO O MECANICOS INSTALADORES DE MAQUINARIA INDUSTRIAL',
    '4131000' => 'MECANICA - INGENIERO O TECNICO EN MECANICA DE VEHICULOS TERRESTRES, AEREOS Y ACUATICOS',
    '4230200' => 'ELECTRICIDAD - INGENIEROS O TECNICOS ELECTRICISTAS',
    '4230500' => 'ELECTRICIDAD - TECNICOS EN REFRIGERACION, AIRE ACONDICIONADO Y CALEFACCION',
    '4330100' => 'ELECTRONICA - MECANICOS DE INSTRUMENTOS INDUSTRIALES',
    '4330200' => 'ELECTRONICA - INGENIERO O TECNICOS EN ELECTRONICA',
    '4430200' => 'INFORMATICA - INGENIERO O TECNICOS PROGRAMADORES EN INFORMATICA',
    '4440100' => 'INFORMATICA - PROFESIONISTAS O TECNICOS DE SISTEMAS DE INFORMACION Y PROCESAMIENTO DE DATOS',
    '4530200' => 'TELECOMUNICACIONES - INGENIERO, INSTALADORES Y REPARADORES DE EQUIPOS Y ACCESORIOS DE TELECOMUNICACIONES',
    '4530500' => 'TELECOMUNICACIONES - TELEGRAFISTAS Y RADIO-OPERADORES',
    '4630100' => 'PROCESOS INDUSTRIALES - INGENIERO O TECNICOS INDUSTRIAL Y DE PRODUCCION',
    '4640300' => 'PROCESOS INDUSTRIALES - INGENIEROS METALURGICOS Y DE MATERIALES',
    '5110100' => 'MINERALES NO METALICOS - OPERADORES O TRABAJADORES DE VIDRIO Y CONCRETO',
    '5121300' => 'MINERALES NO METALICOS - OPERADORES DE MAQUINAS PROCESADORAS DE MINERALES NO METALICOS',
    '5210100' => 'METALES - SUPERVISORES U OPERADORES DE PROCESAMIENTO Y FUNDICION DE METALES',
    '5310700' => 'ALIMENTOS Y BEBIDAS - TRABAJADORES EN LA ELABORACION Y PROCESAMIENTO DE ALIMENTOS, BEBIDAS Y TABACO',
    '5410100' => 'TEXTILES Y PRENDAS DE VESTIR - TRABAJADORES EN LA PRODUCCION DE TEXTILES, PRENDAS DE VESTIR Y CALZADO',
    '5420700' => 'TEXTILES Y PRENDAS DE VESTIR - TRABAJADORES DE REPARACION DE PRENDAS DE VESTIR Y CALZADO',
    '5510100' => 'MADERA, PAPEL, Y PIEL - TRABAJADORES EN LA FABRICACION DE MUEBLES O PRODUCTOS DE MADERA Y/O PIEL',
    '5610200' => 'PRODUCTOS QUIMICOS - TRABAJADORES EN EL PROCESAMIENTO Y FABRICACION DE PRODUCTOS QUIMICOS Y FARMACOQUIMICAS',
    '5710200' => 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - TRABAJADORES EN LA FABRICACION DE PRODUCTOS METALICOS, DE HULE Y PLASTICOS',
    '5720800' => 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - ENSAMBLADORES Y ACABADORES DE PRODUCTOS DE PLASTICO',
    '5720900' => 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - FABRICANTES DE HERRAMIENTAS Y TROQUELES',
    '5721000' => 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - HERREROS Y FORJADORES',
    '5721100' => 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - JOYEROS Y ORFEBRES',
    '5722900' => 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - SOLDADORES Y OXICORTADORES',
    '5730600' => 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - TRABAJADORES EN EL ENSAMBLADO DE VEHICULOS, MOLDEADO, LAMINADO Y MONTAJE DE PIEZAS METALICAS, HULE O PLASTICO',
    '5731100' => 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - SUPERVISORES EN LA FABRICACION Y MONTAJE DE ARTICULOS DEPORTIVOS, DE JUGUETES Y SIMILARES',
    '5810200' => 'PRODUCTOS ELECTRICOS Y ELECTRONICOS - TRABAJADORES EN LA FABRICACION DE PRODUCTOS ELECTRICOS Y ELECTRONICOS',
    '5910400' => 'PRODUCTOS IMPRESOS - TRABAJADORES EN LA ELABORACION DE PRODUCTOS IMPRESOS',
    '6120100' => 'TRANSPORTE FERROVIARIO - CONDUCTORES Y OPERADORES DE TREN SUBTERRANEO Y DE TREN LIGERO',
    '6120200' => 'TRANSPORTE FERROVIARIO - TRABAJADORES DE FERROCARRILES',
    '6220100' => 'TRANSPORTE TERRESTRE - CONDUCTORES DE VEHICULOS DE TRANSPORTE, SERVICIOS DE CARGA Y/O REPARTO',
    '6330100' => 'TRANSPORTE AEREO - COORDINADORES Y SUPERVISORES EN SERVICIOS DE TRANSPORTE AEREO',
    '6330200' => 'TRANSPORTE AEREO - DESPACHADORES DE VUELO Y ESPECIALISTAS EN SERVICIOS AEREOS',
    '6330400' => 'TRANSPORTE AEREO - SUPERVISORES DE SISTEMAS DE COMUNICACION PARA LA AERONAVEGACION',
    '6330500' => 'TRANSPORTE AEREO - PILOTOS DE AVIACION E INSTRUCTORES DE VUELO',
    '6330600' => 'TRANSPORTE AEREO - SOBRECARGOS',
    '6420100' => 'TRANSPORTE MARITIMO Y FLUVIAL - CONDUCTORES DE EMBARCACIONES',
    '6430100' => 'TRANSPORTE MARITIMO Y FLUVIAL - JEFES Y CONTROLADORES DE TRAFICO MARITIMO',
    '6430300' => 'TRANSPORTE MARITIMO Y FLUVIAL - PILOTOS, CAPITANES DE PUERTOS Y OFICIALES DE CUBIERTA',
    '7110200' => 'COMERCIO - DESPACHADORES DE GASOLINERA',
    '7110300' => 'COMERCIO - EMPACADORES DE MERCANCIAS',
    '7110500' => 'COMERCIO - TAQUILLEROS',
    '7110600' => 'COMERCIO - VENDEDORES AMBULANTES',
    '7120100' => 'COMERCIO - CAJEROS REGISTRADORES',
    '7130200' => 'COMERCIO - REPRESENTANTES DE VENTAS POR TELEFONO O POR TELEVISION',
    '7130400' => 'COMERCIO - VENDEDORES ESPECIALIZADOS',
    '7140100' => 'COMERCIO - GERENTES O SUPERVISOR DE ESTABLECIMIENTO COMERCIAL',
    '7140200' => 'COMERCIO - GERENTES O EMPLEADOS DE VENTAS',
    '7210100' => 'ALIMENTACION Y HOSPEDAJE - TRABAJADORES DE SERVICIO DE ALIMENTOS Y BEBIDAS',
    '7230200' => 'ALIMENTACION Y HOSPEDAJE - JEFES DE COCINA, RESTAURANTE Y/O BAR',
    '7240200' => 'ALIMENTACION Y HOSPEDAJE - TRABAJADORES DE SERVICIOS DE ALOJAMIENTO',
    '7330200' => 'TURISMO - COORDINADORES DE OPERACIONES EN AGENCIAS DE VIAJES',
    '7330300' => 'TURISMO - GUIAS DE EXCURSIONES O ECOTURISTICO',
    '7430100' => 'DEPORTE Y ESPARCIMIENTO - ANIMADORES RECREATIVOS',
    '7430200' => 'DEPORTE Y ESPARCIMIENTO - ATLETAS, ENTRENADORES O INSTRUCTORES EN DEPORTE Y RECREACION',
    '7430400' => 'DEPORTE Y ESPARCIMIENTO - OFICIALES, JUECES Y ARBITROS DEPORTIVOS',
    '7530100' => 'SERVICIOS PERSONALES - ESTILISTAS, ESTETICISTAS Y MASAJISTAS',
    '7540100' => 'SERVICIOS PERSONALES - TRABAJADORES DE SERVICIOS FUNERARIOS O CEMENTERIOS',
    '7620100' => 'REPARACION DE ARTICULOS DE USO DOMESTICO Y PERSONAL - CERRAJEROS',
    '7620200' => 'REPARACION DE ARTICULOS DE USO DOMESTICO Y PERSONAL - REPARADORES DE ARTICULOS DE HULE',
    '7630100' => 'REPARACION DE ARTICULOS DE USO DOMESTICO Y PERSONAL - RELOJEROS Y REPARADORES DE RELOJES',
    '7630200' => 'REPARACION DE ARTICULOS DE USO DOMESTICO Y PERSONAL - REPARADORES DE APARATOS ELECTRICOS',
    '7720100' => 'LIMPIEZA - SERVICIOS DE CAMARISTAS Y ASEADORES',
    '7720200' => 'LIMPIEZA - TRABAJADORES DE TINTORERIA Y LAVANDERIA',
    '7720300' => 'LIMPIEZA - FUMIGADORES DE PLAGAS',
    '7810200' => 'SERVICIO POSTAL Y MENSAJERIA - EMPLEADOS DE SERVICIOS DE MENSAJERIA',
    '8120100' => 'BOLSA, BANCA Y SEGUROS - GERENTES O TRABAJADORES DE SERVICIOS Y PRODUCTOS FINANCIEROS',
    '8130500' => 'BOLSA, BANCA Y SEGUROS - VALUADORES',
    '8140100' => 'BOLSA, BANCA Y SEGUROS - AGENTES DE VALORES, PROMOTORES Y CORREDORES DE INVERSION',
    '8210100' => 'ADMINISTRACION - TRABAJADORES DE ARCHIVO, ALMACEN DE INVENTARIOS',
    '8220400' => 'ADMINISTRACION - CAPTURISTA Y OPERADORES DE TELEFONO',
    '8220600' => 'ADMINISTRACION - PAGADORES Y COBRADORES',
    '8230300' => 'ADMINISTRACION - DIRECTORES, GERENTES Y EMPLEADOS DE COMPRAS, FINANZAS, RECURSOS HUMANOS Y SERVICIOS ADMINISTRATIVOS',
    '8240100' => 'ADMINISTRACION - ASISTENTES ADMINISTRATIVOS',
    '8240200' => 'ADMINISTRACION - CONTADORES Y AUDITORES',
    '8240600' => 'ADMINISTRACION - DIRECTORES, GERENTES Y EMPLEADOS DE PRODUCCION',
    '8240700' => 'ADMINISTRACION - DIRECTORES, GERENTES Y EMPLEADOS DE SERVICIOS DE TRANSPORTE',
    '8250100' => 'ADMINISTRACION - CONSULTORES',
    '8250200' => 'ADMINISTRACION - DIRECTORES, GERENTES Y EMPLEADOS DE COMERCIALIZACION',
    '8250800' => 'ADMINISTRACION - DIRECTORES, GERENTES Y EMPLEADOS ADMINISTRATIVOS',
    '8340100' => 'SERVICIOS LEGALES - ABOGADOS Y ASESORES LEGALES',
    '8340300' => 'SERVICIOS LEGALES - NOTARIOS Y CORREDORES PUBLICOS',
    '9120700' => 'SERVICIOS MEDICOS - ENFERMERAS Y/O PARAMEDICOS',
    '9130300' => 'SERVICIOS MEDICOS - DIETISTAS Y NUTRIOLOGOS',
    '9131200' => 'SERVICIOS MEDICOS - TECNICOS DE LABORATORIO MEDICO',
    '9140200' => 'SERVICIOS MEDICOS - DIRECTORES DE INSTITUCIONES EN EL CUIDADO DE LA SALUD',
    '9140400' => 'SERVICIOS MEDICOS - FARMACEUTICOS',
    '9140500' => 'SERVICIOS MEDICOS - FISIOTERAPEUTAS Y QUIROPRACTICOS',
    '9140700' => 'SERVICIOS MEDICOS - MEDICOS ESPECIALISTAS',
    '9140800' => 'SERVICIOS MEDICOS - MEDICOS GENERALES Y FAMILIARES',
    '9230100' => 'INSPECCION - INSPECTORES DE SALUD AMBIENTAL, SANIDAD Y DEL TRABAJO',
    '9230200' => 'INSPECCION - INSPECTORES DE TRANSPORTE DE CARGA Y DE PASAJEROS',
    '9230300' => 'INSPECCION - INSPECTORES FISCALES Y DE PRECIOS',
    '9230400' => 'INSPECCION - INSPECTORES SANITARIOS Y DE CONTROL DE CALIDAD DE PRODUCTOS CARNICOS, PESQUEROS Y AGRICOLAS',
    '9330100' => 'SEGURIDAD SOCIAL - CONSEJEROS DE EMPLEO',
    '9330300' => 'SEGURIDAD SOCIAL - TRABAJADORES DE SERVICIO SOCIAL Y DE LA COMUNIDAD',
    '9420100' => 'PROTECCION DE BIENES Y/O PERSONAS - BOMBEROS',
    '9420300' => 'PROTECCION DE BIENES Y/O PERSONAS - GUARDIAS DE SEGURIDAD',
    '9430100' => 'PROTECCION DE BIENES Y/O PERSONAS - DETECTIVES PRIVADOS',
    '1014010' => 'RADIO, CINE, TELEVISION Y TEATRO - DISEÑADORES GRAFICOS',
    '1014030' => 'RADIO, CINE, TELEVISION Y TEATRO - EDITORES, PERIODISTAS, REPORTEROS Y REDACTORES',
    '1023010' => 'RADIO, CINE, TELEVISION Y TEATRO - ASISTENTES Y/U OPERADORES DE PRODUCCION DE CINE, RADIO Y TELEVISION',
    '1023070' => 'RADIO, CINE, TELEVISION Y TEATRO - LOCUTORES, COMENTARISTAS Y CRONISTAS DE RADIO Y TELEVISION',
    '1024020' => 'RADIO, CINE, TELEVISION Y TEATRO - PRODUCTORES Y DIRECTORES DE CINE, TELEVISION Y TEATRO',
    '1033010' => 'INTERPRETACION ARTISTICA - ACTORES, BAILARINES, MUSICOS, ESCRITORES',
    '1033020' => 'INTERPRETACION ARTISTICA - ARTESANOS',
    '1033040' => 'INTERPRETACION ARTISTICA - FOTOGRAFOS',
    '1034010' => 'INTERPRETACION ARTISTICA - ARTISTAS PLASTICOS',
    '1044010' => 'TRADUCCION E INTERPRETACION LINGUISTICA - INTERPRETES Y/O TRADUCTORES',
    '1052010' => 'PUBLICIDAD, PROPAGANDA Y RELACIONES PUBLICAS - MODELOS Y EDECANES',
    '1054010' => 'PUBLICIDAD, PROPAGANDA Y RELACIONES PUBLICAS - DIRECTORES, GERENTES Y EMPLEADOS DE PUBLICIDAD',
    '1112010' => 'INVESTIGACION - ENCUESTADORES Y CODIFICADORES',
    '1113010' => 'INVESTIGACION - ASISTENTES DE INVESTIGADORES',
    '1113020' => 'INVESTIGACION - QUIMICOS Y/O TECNICOS EN QUIMICA',
    '1114010' => 'INVESTIGACION - BIOLOGOS Y CIENTIFICOS RELACIONADOS',
    '1114020' => 'INVESTIGACION - ECONOMISTAS Y POLITOLOGOS (NO FUNCIONARIOS PUBLICOS)',
    '1114030' => 'INVESTIGACION - FISICOS ASTRONOMOS',
    '1114040' => 'INVESTIGACION - GEOLOGOS, GEOQUIMICOS, GEOFISICOS Y GEOGRAFOS',
    '1114050' => 'INVESTIGACION - INVESTIGADORES Y CONSULTORES EN MERCADOTECNIA',
    '1114060' => 'INVESTIGACION - MATEMATICOS, ESTADISTICOS Y ACTUARIOS',
    '1114070' => 'INVESTIGACION - METEOROLOGOS',
    '1114090' => 'INVESTIGACION - SOCIOLOGOS, ANTROPOLOGOS E HISTORIADORES',
    '1123020' => 'ENSEÑANZA - CAPACITADORES E INSTRUCTORES',
    '1124070' => 'ENSEÑANZA - PROFESORES O DOCENTES',
    '1125010' => 'ENSEÑANZA - DIRECTORES GENERALES DE EDUCACION',
    '1133010' => 'DIFUSION CULTURAL - PROMOTORES DE DIFUSION CULTURAL',
    '1134010' => 'DIFUSION CULTURAL - TRABAJADORES DE BIBLIOTECA, ARCHIVO, MUSEO Y GALERIA DE ARTE',
    '1135010' => 'OTRAS OCUPACIONES - ESTUDIANTE O MENOR DE EDAD SIN OCUPACION',
    '1135080' => 'OTRAS OCUPACIONES - PROPIETARIO, ACCIONISTA O SOCIO',
    '1135020' => 'OTRAS OCUPACIONES - DESEMPLEADO',
    '1135030' => 'OTRAS OCUPACIONES - JUBILADO O PENSIONADO',
    '1135050' => 'OTRAS OCUPACIONES - AMA DE CASA O QUEHACERES DEL HOGAR',
    '1135060' => 'OTRAS OCUPACIONES - MINISTROS DE CULTO RELIGIOSO (SACERDOTE, PASTOR, MONJA, ETC)',
    '1135070' => 'OTRAS OCUPACIONES - AGENTE ADUANAL',
    '1136010' => 'SECTOR PUBLICO - EMPLEADO DEL PODER EJECUTIVO FEDERAL',
    '1136020' => 'SECTOR PUBLICO - EMPLEADO PODER EJECUTIVO ESTATAL O DEL DISTRITO FEDERAL',
    '1136030' => 'SECTOR PUBLICO - EMPLEADO DEL PODER EJECUTIVO MUNICIPAL O DELEGACIONAL',
    '1136040' => 'SECTOR PUBLICO - EMPLEADO DEL PODER JUDICIAL FEDERAL',
    '1136070' => 'SECTOR PUBLICO - EMPLEADO DEL PODER JUDICIAL ESTATAL O DEL DISTRITO FEDERAL',
    '1136050' => 'SECTOR PUBLICO - EMPLEADO DEL PODER LEGISLATIVO FEDERAL',
    '1136060' => 'SECTOR PUBLICO - EMPLEADO DEL PODER LEGISLATIVO ESTATAL O DEL DISTRITO FEDERAL',
    '1136090' => 'SECTOR PUBLICO - EJERCITO, ARMADA Y FUERZA AEREA',
    '1136080' => 'ORGANISMOS INTERNACIONALES Y EXTRATERRITORIALES - EMPLEADOS DE ORGANISMOS INTERNACIONALES Y EXTRATERRITORIALES',
];

/**
 * Genera opciones HTML <option> desde un catálogo
 */
function dinCatalogoOptions(string $catalogoName, string $selectedValue = ''): string {
    global $DIN_CATALOGOS;
    $cat = $DIN_CATALOGOS[$catalogoName] ?? [];
    $html = '<option value="">-- Seleccione --</option>';
    foreach ($cat as $clave => $descripcion) {
        $sel = ((string)$clave === (string)$selectedValue) ? ' selected' : '';
        $html .= '<option value="' . htmlspecialchars($clave) . '"' . $sel . '>'
                . htmlspecialchars($clave . ' - ' . $descripcion)
                . '</option>';
    }
    return $html;
}

/**
 * Devuelve catálogos como JSON (para uso en JS si se necesita)
 */
function dinCatalogosJson(): string {
    global $DIN_CATALOGOS;
    return json_encode($DIN_CATALOGOS, JSON_UNESCAPED_UNICODE);
}
