<?php
/**
 * Catálogos INM (V Bis / Inmuebles).
 * Base operativa tomada de instructivo_inm.xlsx.
 */

if (!isset($INM_CATALOGOS) || !is_array($INM_CATALOGOS)) {
    $INM_CATALOGOS = [];
}

$INM_CATALOGOS['clave_actividad'] = [
    'INM' => 'Recepción de recursos destinados a desarrollo inmobiliario para venta o renta',
];

$INM_CATALOGOS['prioridad'] = [
    '1' => '1 - Normal',
    '2' => '2 - 24 horas con operaciones',
];

$INM_CATALOGOS['exento'] = [
    '0' => 'No',
    '1' => 'Sí',
];

$INM_CATALOGOS['tipo_alerta'] = [
    '100' => 'Sin alerta.',
    '3101' => 'El cliente se rehúsa a proporcionar documentos personales que lo identifiquen.',
    '3102' => 'El pago por el inmueble es realizado por un tercero sin relación aparente con el cliente.',
    '3103' => 'El cliente o personas relacionadas con él realizan múltiples operaciones en un periodo muy corto sin razón aparente.',
    '3104' => 'Al cliente parece no importarle pagar precios superiores a los del mercado con la finalidad de que la operación se realice fuera de los parámetros establecidos.',
    '3105' => 'De acuerdo con medios informativos u otras fuentes de información pública, se tiene conocimiento o sospecha de que el cliente, un familiar o persona relacionada, está vinculado con actividades ilícitas o se encuentra bajo proceso de investigación.',
    '3106' => 'El cliente no quiere ser relacionado con la compra del inmueble.',
    '3107' => 'La operación no es acorde con la actividad económica o giro mercantil declarado por el cliente.',
    '3108' => 'El cliente solicita que se realice la operación por medio de un contrato privado, donde no hay intención de registrarlo ante notario, o cuando esta intención se expresa, no se lleva a cabo finalmente.',
    '3109' => 'Transacciones sucesivas de compra y venta de la misma propiedad en un periodo corto de tiempo, con cambios injustificados del valor de la misma.',
    '3110' => 'La operación se lleva a cabo a un valor de venta o compra significativamente diferente a partir del valor real de la propiedad o a los valores de mercado.',
    '3111' => 'Hay indicios, o certeza, que las partes no están actuando en nombre propio y están tratando de ocultar la identidad del cliente real.',
    '3112' => 'Uso de divisas en efectivo sin justificación alguna.',
    '3113' => 'El cliente liquida la operación por medio de una transferencia proveniente de un país extranjero.',
    '3114' => 'El cliente insiste en liquidar o pagar la operación en efectivo rebasando el umbral permitido en la Ley.',
    '3115' => 'El cliente intenta sobornar, extorsionar o amenaza al vendedor con el fin de realizar la operación fuera de los parámetros establecidos, o con la finalidad de evitar el envío del Aviso.',
    '3116' => 'La información y documentación presentada por el cliente es inconsistente o de difícil verificación por parte del Sujeto Obligado.',
    '3117' => 'Se tiene sospecha de que algunos intermediarios dentro del sistema financiero están coludidos con el cliente.',
    '3118' => 'El cliente es un Fideicomiso y se niega a proporcionar información sobre el beneficiario controlador.',
    '3119' => 'El cliente opera en grupos sin que exista algún parentesco o relación entre ellos.',
    '3120' => 'El cliente pretende pagar o liquidar la operación con monedas virtuales.',
    '9999' => 'Otra alerta.',
];

$INM_CATALOGOS['tipo_operacion'] = [
    '501' => 'Compra Venta de Inmuebles',
];

$INM_CATALOGOS['figura_cliente'] = [
    '1' => 'Vendedor',
    '2' => 'Comprador',
];

$INM_CATALOGOS['figura_so'] = [
    '1' => 'Vendedor',
    '2' => 'Comprador',
    '3' => 'Intermediario',
];

$INM_CATALOGOS['tipo_inmueble'] = [
    '1' => 'Casa / Casa en condominio',
    '2' => 'Departamento',
    '3' => 'Edificio habitacional',
    '4' => 'Edificio comercial',
    '5' => 'Edificio oficinas',
    '6' => 'Local comercial independiente',
    '7' => 'Local en centro comercial',
    '8' => 'Oficina',
    '9' => 'Bodega comercial',
    '10' => 'Bodega industrial',
    '11' => 'Nave Industrial',
    '12' => 'Terreno urbano habitacional',
    '13' => 'Terreno no urbano habitacional',
    '14' => 'Terreno urbano comercial o industrial',
    '15' => 'Terreno no urbano comercial o industrial',
    '16' => 'Terreno ejidal',
    '17' => 'Rancho/Hacienda/Quinta',
    '18' => 'Huerta',
    '99' => 'Otro',
];

$INM_CATALOGOS['forma_pago'] = [
    '1' => 'Contado',
    '2' => 'Diferido o en parcialidades',
    '3' => 'Dación en pago',
    '4' => 'Préstamo o crédito',
    '5' => 'Permuta',
];

$INM_CATALOGOS['instrumento_monetario'] = [
    '1' => 'Efectivo',
    '2' => 'Tarjeta de Crédito',
    '3' => 'Tarjeta de Débito',
    '4' => 'Tarjeta de Prepago',
    '5' => 'Cheque Nominativo',
    '6' => 'Cheque de Caja',
    '7' => 'Cheques de Viajero',
    '8' => 'Transferencia Interbancaria',
    '9' => 'Transferencia Misma Institución',
    '10' => 'Transferencia Internacional',
    '11' => 'Orden de Pago',
    '12' => 'Giro',
    '13' => 'Oro o Platino Amonedados',
    '14' => 'Plata Amonedada',
    '15' => 'Metales Preciosos',
    '16' => 'Activos Virtuales',
    '99' => 'Otros',
];

$INM_CATALOGOS['moneda'] = [
    '1' => 'MXN - Peso mexicano - México',
    '2' => 'USD - Dólar estadounidense - Estados Unidos',
    '3' => 'EUR - Euro - Unión Europea',
    '4' => 'AED - Dírham de los Emiratos Árabes Unidos - Emiratos Árabes Unidos',
    '5' => 'AFN - Afgani afgano - Afganistán',
    '6' => 'ALL - Lek albanés - Albania',
    '7' => 'AMD - Dram armenio - Armenia',
    '8' => 'ANG - Florín antillano neerlandés - Antillas Neerlandesas',
    '9' => 'AOA - Kwanza angoleño - Angola',
    '10' => 'ARS - Peso argentino - Argentina',
    '11' => 'AUD - Dólar australiano - Australia',
    '12' => 'AWG - Florín arubeño - Aruba',
    '13' => 'AZM - Manat azerbaiyano - Azerbaiyán',
    '14' => 'AZN - Manat azerbaiyano - Azerbaiyán',
    '15' => 'BAM - Marco convertible de Bosnia-Herzegovina - Bosnia y Herzegovina',
    '16' => 'BBD - Dólar de Barbados - Barbados',
    '17' => 'BDT - Taka de Bangladésh - Bangladésh',
    '18' => 'BGN - Lev búlgaro - Bulgaria',
    '19' => 'BHD - Dinar bareiní - Bahréin',
    '20' => 'BIF - Franco burundés - Burundi',
    '21' => 'BMD - Dólar de Bermudas - Bermudas',
    '22' => 'BND - Dólar de Brunéi - Brunéi',
    '23' => 'BOB - Boliviano - Bolivia',
    '24' => 'BRL - Real brasileño - Brasil',
    '25' => 'BSD - Dólar bahameño - Bahamas',
    '26' => 'BTN - Ngultrum de Bután - Bután',
    '27' => 'BWP - Pula de Botsuana - Botsuana',
    '28' => 'BYR - Rublo bielorruso - Belarús',
    '29' => 'BZD - Dólar de Belice - Belice',
    '30' => 'CAD - Dólar canadiense - Canadá',
    '31' => 'CDF - Franco congoleño - República Democrática del Congo',
    '32' => 'CHF - Franco suizo - Suiza',
    '33' => 'CLP - Peso chileno - Chile',
    '34' => 'CNY - Yuan chino - China',
    '35' => 'COP - Peso colombiano - Colombia',
    '36' => 'CRC - Colón costarricense - Costa Rica',
    '37' => 'CSD - Dinar serbio - Serbia',
    '38' => 'CUC - Peso cubano convertible - Cuba',
    '39' => 'CUP - Peso cubano - Cuba',
    '40' => 'CVE - Escudo caboverdiano - Cabo Verde',
    '41' => 'CZK - Corona checa - Chequia',
    '42' => 'DJF - Franco yibutiano - Yibuti',
    '43' => 'DKK - Corona danesa - Dinamarca',
    '44' => 'DOP - Peso dominicano - República Dominicana',
    '45' => 'DZD - Dinar argelino - Argelia',
    '46' => 'EGP - Libra egipcia - Egipto',
    '47' => 'ERN - Nakfa eritreo - Eritrea',
    '48' => 'ETB - Birr etíope - Etiopía',
    '49' => 'FJD - Dólar fiyiano - Fiyi',
    '50' => 'FKP - Libra malvinense - Islas Malvinas',
    '51' => 'GBP - Libra esterlina - Reino Unido',
    '52' => 'GEL - Lari georgiano - Georgia',
    '53' => 'GHS - Cedi ghanés - Ghana',
    '54' => 'GIP - Libra de Gibraltar - Gibraltar',
    '55' => 'GMD - Dalasi gambiano - Gambia',
    '56' => 'GNF - Franco guineano - Guinea',
    '57' => 'GTQ - Quetzal guatemalteco - Guatemala',
    '58' => 'GYD - Dólar guyanés - Guyana',
    '59' => 'HKD - Dólar de Hong Kong - Hong Kong',
    '60' => 'HNL - Lempira hondureño - Honduras',
    '61' => 'HRK - Kuna croata - Croacia',
    '62' => 'HTG - Gourde haitiano - Haití',
    '63' => 'HUF - Forint húngaro - Hungría',
    '64' => 'IDR - Rupia indonesia - Indonesia',
    '65' => 'ILS - Nuevo shéquel israelí - Israel',
    '66' => 'INR - Rupia india - India',
    '67' => 'IQD - Dinar iraquí - Irak',
    '68' => 'IRR - Rial iraní - Irán',
    '69' => 'ISK - Króna islandesa - Islandia',
    '70' => 'JMD - Dólar jamaicano - Jamaica',
    '71' => 'JOD - Dinar jordano - Jordania',
    '72' => 'JPY - Yen japonés - Japón',
    '73' => 'KES - Chelín keniano - Kenia',
    '74' => 'KGS - Som kirguís - Kirguistán',
    '75' => 'KHR - Riel camboyano - Camboya',
    '76' => 'KMF - Franco comoriano - Comoras',
    '77' => 'KPW - Won norcoreano - Corea del Norte',
    '78' => 'KRW - Won surcoreano - Corea del Sur',
    '79' => 'KWD - Dinar kuwaití - Kuwait',
    '80' => 'KYD - Dólar caimano - Islas Caimán',
    '81' => 'KZT - Tenge kazajo - Kazajistán',
    '82' => 'LAK - Kip lao - Laos',
    '83' => 'LBP - Libra libanesa - Líbano',
    '84' => 'LKR - Rupia de Sri Lanka - Sri Lanka',
    '85' => 'LRD - Dólar liberiano - Liberia',
    '86' => 'LSL - Loti lesotense - Lesoto',
    '87' => 'LTL - Litas lituano - Lituania',
    '88' => 'LVL - Lat letón - Letonia',
    '89' => 'LYD - Dinar libio - Libia',
    '90' => 'MAD - Dírham marroquí - Marruecos',
    '91' => 'MDL - Leu moldavo - Moldova',
    '92' => 'MGA - Ariary malgache - Madagascar',
    '93' => 'MKD - Denar macedonio - Macedonia',
    '94' => 'MMK - Kyat birmano - Myanmar',
    '95' => 'MNT - Tugrik mongol - Mongolia',
    '96' => 'MOP - Pataca de Macao - Macao',
    '97' => 'MRO - Ouguiya mauritano - Mauritania',
    '98' => 'MUR - Rupia mauricia - Mauricio',
    '99' => 'MVR - Rufiyaa maldiva - Maldivas',
    '100' => 'MWK - Kwacha malauí - Malaui',
    '101' => 'MYR - Ringgit malayo - Malasia',
    '102' => 'MZN - Metical mozambiqueño - Mozambique',
    '103' => 'NAD - Dólar namibio - Namibia',
    '104' => 'NGN - Naira nigeriana - Nigeria',
    '105' => 'NIO - Córdoba nicaragüense - Nicaragua',
    '106' => 'NOK - Corona noruega - Noruega',
    '107' => 'NPR - Rupia nepalesa - Nepal',
    '108' => 'NZD - Dólar neozelandés - Nueva Zelanda',
    '109' => 'OMR - Rial omaní - Omán',
    '110' => 'PAB - Balboa panameño - Panamá',
    '111' => 'PEN - Nuevo sol peruano - Perú',
    '112' => 'PGK - Kina de Papúa Nueva Guinea - Papúa Nueva Guinea',
    '113' => 'PHP - Peso filipino - Filipinas',
    '114' => 'PKR - Rupia pakistaní - Pakistán',
    '115' => 'PLN - Zloty polaco - Polonia',
    '116' => 'PYG - Guaraní paraguayo - Paraguay',
    '117' => 'QAR - Rial catarí - Catar',
    '118' => 'RON - Leu rumano - Rumania',
    '119' => 'RSD - Dinar serbio - Serbia',
    '120' => 'RUB - Rublo ruso - Rusia',
    '121' => 'RWF - Franco ruandés - Ruanda',
    '122' => 'SAR - Riyal saudí - Arabia Saudí',
    '123' => 'SBD - Dólar de las Islas Salomón - Islas Salomón',
    '124' => 'SCR - Rupia de Seychelles - Seychelles',
    '125' => 'SDG - Dinar sudanés - Sudán',
    '126' => 'SEK - Corona sueca - Suecia',
    '127' => 'SGD - Dólar de Singapur - Singapur',
    '128' => 'SHP - Libra de Santa Helena - Santa Elena',
    '129' => 'SLL - Leone de Sierra Leona - Sierra Leona',
    '130' => 'SOS - Chelín somalí - Somalia',
    '131' => 'SRD - Dólar surinamés - Surinam',
    '132' => 'SSP - Libra de Sudán del Sur - Sudán del Sur',
    '133' => 'STD - Dobra de Santo Tomé y Príncipe - Santo Tomé y Príncipe',
    '134' => 'SVC - Colón salvadoreño - El Salvador',
    '135' => 'SYP - Libra siria - Siria',
    '136' => 'SZL - Lilangeni suazi - Suazilandia',
    '137' => 'THB - Baht tailandés - Tailandia',
    '138' => 'TJS - Somoni tayiko - Tayikistán',
    '139' => 'TMT - Manat turcomano - Turkmenistán',
    '140' => 'TND - Dinar tunecino - Túnez',
    '141' => 'TOP - Paʻanga tongano - Tonga',
    '142' => 'TRY - Lira turca - Turquía',
    '143' => 'TTD - Dólar de Trinidad y Tobago - Trinidad y Tobago',
    '144' => 'TWD - Dólar taiwanés - Taiwán',
    '145' => 'TZS - Chelín tanzano - Tanzania',
    '146' => 'UAH - Grivna ucraniana - Ucrania',
    '147' => 'UGX - Chelín ugandés - Uganda',
    '148' => 'UYU - Peso uruguayo - Uruguay',
    '149' => 'UZS - Som uzbeko - Uzbekistán',
    '150' => 'VEF - Bolívar fuerte venezolano - Venezuela',
    '151' => 'VND - Dong vietnamita - Vietnam',
    '152' => 'VUV - Vatu vanuatense - Vanuatu',
    '153' => 'WST - Tala samoano - Samoa',
    '154' => 'YER - Rial yemení - Yemen',
    '155' => 'ZAR - Rand sudafricano - Sudáfrica',
    '156' => 'ZMK - Kwacha zambiano - Zambia',
    '157' => 'ZMW - Kwacha zambiano - Zambia',
    '158' => 'ZWL - Dólar zimbabuense - Zimbabue',
    '159' => 'MXA - Centenario - México',
    '160' => 'MXB - Azteca - México',
    '161' => 'MXC - Hidalgo - México',
    '162' => 'MXD - 1/2 Hidalgo - México',
    '163' => 'MXE - 1/4 Hidalgo - México',
    '164' => 'MXF - 1/5 Hidalgo - México',
    '165' => 'MXG - 1 OZ Libertad de oro - México',
    '166' => 'MXH - 1/2 OZ Libertad de oro - México',
    '167' => 'MXI - 1/4 OZ Libertad de oro - México',
    '168' => 'MXJ - 1/10 OZ Libertad de oro - México',
    '169' => 'MXK - 1/20 OZ Libertad de oro - México',
    '170' => 'MXL - 1 OZ Libertad de plata - México',
    '171' => 'MXM - 1/2 OZ Libertad de plata - México',
    '172' => 'MXN - 1/4 OZ Libertad de plata - México',
    '173' => 'MXO - 1/10 OZ Libertad de plata - México',
    '174' => 'MXP - 1/20 OZ Libertad de plata - México',
    '175' => 'XAG - Onza de plata - N/A',
    '176' => 'XAU - Onza de oro - N/A',
    '177' => 'XFO - Franco de oro (Special settlement currency) - N/A',
    '178' => 'XPD - Onza de paladio - N/A',
    '179' => 'XPT - Onza de platino - N/A',
    '180' => 'XAF - Franco CFA de África Central - N/A',
    '181' => 'XCD - Dólar del Caribe Oriental - N/A',
    '182' => 'XFU - Franco UIC (Special settlement currency) - N/A',
    '183' => 'XOF - Franco CFA de África Occidental - N/A',
    '184' => 'XPF - Franco CFP - N/A',
];

$INM_CATALOGOS['entidad_federativa'] = [
    '1' => 'Aguascalientes',
    '2' => 'Baja California',
    '3' => 'Baja California Sur',
    '4' => 'Campeche',
    '5' => 'Coahuila de Zaragoza',
    '6' => 'Colima',
    '7' => 'Chiapas',
    '8' => 'Chihuahua',
    '9' => 'Distrito Federal',
    '10' => 'Durango',
    '11' => 'Guanajuato',
    '12' => 'Guerrero',
    '13' => 'Hidalgo',
    '14' => 'Jalisco',
    '15' => 'México',
    '16' => 'Michoacán de Ocampo',
    '17' => 'Morelos',
    '18' => 'Nayarit',
    '19' => 'Nuevo León',
    '20' => 'Oaxaca',
    '21' => 'Puebla',
    '22' => 'Querétaro',
    '23' => 'Quintana Roo',
    '24' => 'San Luis Potosí',
    '25' => 'Sinaloa',
    '26' => 'Sonora',
    '27' => 'Tabasco',
    '28' => 'Tamaulipas',
    '29' => 'Tlaxcala',
    '30' => 'Veracruz de Ignacio de la Llave',
    '31' => 'Yucatán',
    '32' => 'Zacatecas',
];

$INM_CATALOGOS['pais'] = [];
$INM_CATALOGOS['actividad_economica'] = [
    '1000000' => 'NO APLICA',
];
$INM_CATALOGOS['giro_mercantil'] = [
    '1000000' => 'NO APLICA',
];

if (!function_exists('inmCatalogoOptions')) {
    function inmCatalogoOptions(string $key, ?string $selected = null, ?callable $labeler = null, bool $withPlaceholder = true): string
    {
        global $INM_CATALOGOS;
        $items = $INM_CATALOGOS[$key] ?? [];
        $html = $withPlaceholder ? '<option value="">-- Seleccione --</option>' : '';
        foreach ($items as $k => $v) {
            $label = $labeler ? $labeler((string)$k, (string)$v) : ((string)$k . ' - ' . (string)$v);
            $sel = ((string)$selected === (string)$k) ? ' selected' : '';
            $html .= '<option value="' . htmlspecialchars((string)$k, ENT_QUOTES, 'UTF-8') . '"' . $sel . '>'
                . htmlspecialchars($label, ENT_QUOTES, 'UTF-8') . '</option>';
        }
        return $html;
    }
}
