<?php
/**
 * Catálogos TCV (Fracción X / Traslado o custodia de dinero o valores).
 * Los catálogos específicos quedan separados para sustituirlos por los oficiales UIF.
 */

require_once __DIR__ . '/din_catalogos.php';
require_once __DIR__ . '/inm_catalogos.php';

if (!isset($TCV_CATALOGOS) || !is_array($TCV_CATALOGOS)) {
    $TCV_CATALOGOS = [];
}

$TCV_CATALOGOS['clave_actividad'] = [
    'TCV' => 'Traslado o custodia de dinero o valores',
];

$TCV_CATALOGOS['prioridad'] = [
    '1' => '1 - Normal',
    '2' => '2 - 24 horas con operaciones',
];

$TCV_CATALOGOS['exento'] = [
    '0' => 'No',
    '1' => 'Sí',
];

$TCV_CATALOGOS['tipo_alerta'] = [
    '100' => 'Sin alerta.',
    '3201' => 'El cliente o usuario se rehúsa a proporcionar documentos personales que lo identifiquen.',
    '3202' => 'El servicio otorgado es pagado por un tercero sin relación aparente con el cliente o usuario.',
    '3203' => 'Custodia o traslado de bienes poco comunes o que no coinciden con la actividad económica o giro mercantil del cliente o usuario.',
    '3204' => 'El cliente o usuario se rehúsa a revelar cuáles son los bienes transportados o custodiados sin razón aparente.',
    '3205' => 'De acuerdo con medios informativos u otras fuentes de información pública, se tiene conocimiento o sospecha de que el cliente, un familiar o persona relacionada, está vinculado con actividades ilícitas o se encuentra bajo proceso de investigación.',
    '3206' => 'El cliente o usuario parece no importarle pagar precios superiores a los del mercado con el fin de que el servicio se realice fuera de los parámetros establecidos.',
    '3207' => 'El cliente o usuario no quiere ser relacionado con la contratación del servicio.',
    '3208' => 'Hay indicios, o certeza, que las partes no están actuando en nombre propio y están tratando de ocultar la identidad del cliente o usuario real.',
    '3209' => 'El cliente o usuario liquida la operación por medio de una transferencia proveniente de un país extranjero, cuando no existe justificación para ello.',
    '3210' => 'El cliente o usuario intenta sobornar, extorsionar o amenaza con el fin de realizar la operación fuera de los parámetros establecidos, o con la finalidad de evitar el envío del Aviso.',
    '3211' => 'La información y documentación presentada por el cliente o usuario es inconsistente o de difícil verificación por parte del Sujeto Obligado.',
    '3212' => 'El cliente o usuario solicita, en su mayoría y de forma continua, traslado de metales preciosos sin que su actividad lo justifique.',
    '3213' => 'El cliente o usuario o personas relacionadas con él realizan múltiples operaciones en un periodo muy corto sin razón aparente.',
    '3214' => 'Traslado habitual de valores a nombre de diferentes personas en el mismo domicilio de entrega, sin causa que lo justifique.',
    '3215' => 'Clientes o usuarios personas morales que solicitan traslado de efectivo que sean recogidos o entregados en casas habitación u oficinas virtuales.',
    '3216' => 'El monto trasladado excede significativamente el promedio de los servicios solicitados por el cliente con anterioridad.',
    '3217' => 'El cliente evita que el domicilio exacto de recepción o entrega de los valores quede registrado, proporcionando la información por otros medios.',
    '3218' => 'El monto del numerario o valores trasladados no corresponde a la magnitud del negocio o la actividad declarada del cliente.',
    '9999' => 'Otra alerta.',
];

$TCV_CATALOGOS['tipo_operacion'] = [
    '1001' => '1 Traslado',
    '1002' => '2 Custodia',
    '1003' => '3 Traslado y Custodia',
];

$TCV_CATALOGOS['tipo_servicio'] = [
    '1' => 'Aéreo',
    '2' => 'Terrestre',
    '3' => 'Marítimo',
    '4' => 'Mixto',
];

$TCV_CATALOGOS['tipo_valor'] = [
    '1' => 'Metales Preciosos',
    '2' => 'Piedras preciosas',
    '3' => 'Joyas y/o relojes',
    '4' => 'Obras de arte',
    '5' => 'Vales o cupones',
    '6' => 'Boletos, fichas o cualquier otro tipo de comprobante similar para la práctica de juegos, concursos o sorteos',
    '8' => 'Títulos de crédito',
    '99' => 'Otros',
];

$TCV_CATALOGOS['instrumento_monetario'] = [
    '1' => 'Efectivo',
    '2' => 'Tarjeta de Crédito',
    '3' => 'Tarjeta de Débito',
    '4' => 'Tarjeta de Prepago',
    '5' => 'Cheque Nominativo',
    '6' => 'Cheque de Caja',
    '7' => 'Cheques de Viajero',
    '13' => 'Oro o Platino Amonedados',
    '14' => 'Plata Amonedada',
    '15' => 'Metales Preciosos',
];

$TCV_CATALOGOS['moneda'] = $INM_CATALOGOS['moneda'] ?? [];

$TCV_CATALOGOS['pais'] = [
    'AF' => 'AFGANISTÁN',
    'AL' => 'ALBANIA',
    'DE' => 'ALEMANIA',
    'AD' => 'ANDORRA',
    'AO' => 'ANGOLA',
    'AI' => 'ANGUILA',
    'AQ' => 'ANTÁRTIDA',
    'AG' => 'ANTIGUA Y BARBUDA',
    'SA' => 'ARABIA SAUDITA',
    'DZ' => 'ARGELIA',
    'AR' => 'ARGENTINA',
    'AM' => 'ARMENIA',
    'AW' => 'ARUBA',
    'AU' => 'AUSTRALIA',
    'AT' => 'AUSTRIA',
    'AZ' => 'AZERBAIYÁN',
    'BS' => 'BAHAMAS',
    'BH' => 'BAHRÉIN',
    'BD' => 'BANGLADÉS',
    'BB' => 'BARBADOS',
    'BE' => 'BÉLGICA',
    'BZ' => 'BELICE',
    'BJ' => 'BENÍN',
    'BM' => 'BERMUDAS',
    'BY' => 'BIELORRUSIA',
    'MM' => 'BIRMANIA (MYANMAR)',
    'BO' => 'BOLIVIA',
    'BA' => 'BOSNIA Y HERZEGOVINA',
    'BW' => 'BOTSUANA',
    'BR' => 'BRASIL',
    'BN' => 'BRUNÉI DARUSSALAM',
    'BG' => 'BULGARIA',
    'BF' => 'BURKINA FASO',
    'BI' => 'BURUNDI',
    'BT' => 'BUTÁN',
    'CV' => 'CABO VERDE',
    'KH' => 'CAMBOYA',
    'CM' => 'CAMERÚN',
    'CA' => 'CANADÁ',
    'TD' => 'CHAD',
    'CL' => 'CHILE',
    'CN' => 'CHINA',
    'CY' => 'CHIPRE',
    'VA' => 'CIUDAD DEL VATICANO',
    'CO' => 'COLOMBIA',
    'KM' => 'COMORAS',
    'CD' => 'CONGO (REPÚBLICA DEMOCRÁTICA DEL)',
    'CG' => 'CONGO (REPÚBLICA DEL)',
    'KP' => 'COREA (REPÚBLICA POPULAR DEMOCRÁTICA DE)',
    'KR' => 'COREA (REPÚBLICA DE)',
    'CI' => 'COSTA DE MARFIL',
    'CR' => 'COSTA RICA',
    'HR' => 'CROACIA',
    'CU' => 'CUBA',
    'DK' => 'DINAMARCA',
    'DM' => 'DOMINICA',
    'EC' => 'ECUADOR',
    'EG' => 'EGIPTO',
    'SV' => 'EL SALVADOR',
    'AE' => 'EMIRATOS ÁRABES UNIDOS',
    'ER' => 'ERITREA',
    'SK' => 'ESLOVAQUIA',
    'SI' => 'ESLOVENIA',
    'ES' => 'ESPAÑA',
    'US' => 'ESTADOS UNIDOS DE AMÉRICA',
    'EE' => 'ESTONIA',
    'ET' => 'ETIOPÍA',
    'RU' => 'FEDERACIÓN RUSA',
    'FJ' => 'FIJI',
    'PH' => 'FILIPINAS',
    'FI' => 'FINLANDIA',
    'FR' => 'FRANCIA',
    'GA' => 'GABÓN',
    'GM' => 'GAMBIA',
    'GE' => 'GEORGIA',
    'GH' => 'GHANA',
    'GI' => 'GIBRALTAR',
    'GD' => 'GRANADA',
    'GR' => 'GRECIA',
    'GL' => 'GROENLANDIA',
    'GP' => 'GUADALUPE',
    'GU' => 'GUAM',
    'GT' => 'GUATEMALA',
    'GF' => 'GUAYANA FRANCESA',
    'GG' => 'GUERNSEY',
    'GN' => 'GUINEA',
    'GQ' => 'GUINEA ECUATORIAL',
    'GW' => 'GUINEA-BISSAU',
    'GY' => 'GUYANA',
    'HT' => 'HAITÍ',
    'HN' => 'HONDURAS',
    'HK' => 'HONG KONG',
    'HU' => 'HUNGRÍA',
    'IN' => 'INDIA',
    'ID' => 'INDONESIA',
    'IR' => 'IRÁN (REPÚBLICA ISLÁMICA DE)',
    'IQ' => 'IRAK',
    'IE' => 'IRLANDA',
    'IS' => 'ISLANDIA',
    'AX' => 'ISLAS ALAND',
    'KY' => 'ISLAS CAIMÁN',
    'CK' => 'ISLAS COOK',
    'FO' => 'ISLAS FAROE',
    'FK' => 'ISLAS MALVINAS',
    'MP' => 'ISLAS MARIANAS DEL NORTE',
    'MH' => 'ISLAS MARSHALL',
    'NF' => 'ISLAS NORFOLK',
    'PN' => 'ISLAS PITCAIRN',
    'SB' => 'ISLAS SALOMÓN',
    'TC' => 'ISLAS TURCAS Y CAICOS',
    'VG' => 'ISLAS VÍRGENES BRITÁNICAS',
    'VI' => 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS',
    'IL' => 'ISRAEL',
    'IT' => 'ITALIA',
    'JM' => 'JAMAICA',
    'JP' => 'JAPÓN',
    'JE' => 'JERSEY',
    'JO' => 'JORDANIA',
    'KZ' => 'KAZAJISTÁN',
    'KE' => 'KENIA',
    'KG' => 'KIRGUISTÁN',
    'KI' => 'KIRIBATI',
    'KW' => 'KUWAIT',
    'LA' => 'LAOS',
    'LS' => 'LESOTO',
    'LV' => 'LETONIA',
    'LB' => 'LÍBANO',
    'LR' => 'LIBERIA',
    'LY' => 'LIBIA',
    'LI' => 'LIECHTENSTEIN',
    'LT' => 'LITUANIA',
    'LU' => 'LUXEMBURGO',
    'MO' => 'MACAO',
    'MK' => 'MACEDONIA',
    'MG' => 'MADAGASCAR',
    'MY' => 'MALASIA',
    'MW' => 'MALAUI',
    'MV' => 'MALDIVAS',
    'ML' => 'MALÍ',
    'MT' => 'MALTA',
    'MA' => 'MARRUECOS',
    'MQ' => 'MARTINICA',
    'MU' => 'MAURICIO',
    'MR' => 'MAURITANIA',
    'YT' => 'MAYOTTE',
    'MX' => 'MÉXICO',
    'FM' => 'MICRONESIA',
    'MD' => 'MOLDAVIA',
    'MC' => 'MÓNACO',
    'MN' => 'MONGOLIA',
    'ME' => 'MONTENEGRO',
    'MS' => 'MONTSERRAT',
    'MZ' => 'MOZAMBIQUE',
    'NA' => 'NAMIBIA',
    'NR' => 'NAURU',
    'NP' => 'NEPAL',
    'NI' => 'NICARAGUA',
    'NE' => 'NÍGER',
    'NG' => 'NIGERIA',
    'NU' => 'NIUE',
    'NO' => 'NORUEGA',
    'NC' => 'NUEVA CALEDONIA',
    'NZ' => 'NUEVA ZELANDA',
    'OM' => 'OMÁN',
    'NL' => 'PAÍSES BAJOS',
    'PK' => 'PAKISTÁN',
    'PW' => 'PALAOS',
    'PS' => 'PALESTINA',
    'PA' => 'PANAMÁ',
    'PG' => 'PAPÚA NUEVA GUINEA',
    'PY' => 'PARAGUAY',
    'PE' => 'PERÚ',
    'PF' => 'POLINESIA FRANCESA',
    'PL' => 'POLONIA',
    'PT' => 'PORTUGAL',
    'PR' => 'PUERTO RICO',
    'QA' => 'QATAR',
    'GB' => 'REINO UNIDO',
    'CF' => 'REPÚBLICA CENTROAFRICANA',
    'CZ' => 'REPÚBLICA CHECA',
    'DO' => 'REPÚBLICA DOMINICANA',
    'SS' => 'REPÚBLICA DE SUDÁN DEL SUR',
    'RW' => 'RUANDA',
    'RO' => 'RUMANÍA',
    'EH' => 'SÁHARA OCCIDENTAL',
    'WS' => 'SAMOA',
    'AS' => 'SAMOA AMERICANA',
    'SM' => 'SAN MARINO',
    'KN' => 'SAN CRISTÓBAL Y NIEVES',
    'PM' => 'SAN PEDRO Y MIQUELÓN',
    'VC' => 'SAN VICENTE Y LAS GRANADINAS',
    'SH' => 'SANTA HELENA, ASCENSIÓN Y TRISTÁN DE ACUÑA',
    'LC' => 'SANTA LUCÍA',
    'ST' => 'SANTO TOMÉ Y PRÍNCIPE',
    'SN' => 'SENEGAL',
    'RS' => 'SERBIA',
    'SC' => 'SEYCHELLES',
    'SL' => 'SIERRA LEONA',
    'SG' => 'SINGAPUR',
    'SY' => 'SIRIA',
    'SO' => 'SOMALIA',
    'LK' => 'SRI LANKA',
    'SZ' => 'SUAZILANDIA',
    'ZA' => 'SUDÁFRICA',
    'SD' => 'SUDÁN',
    'SE' => 'SUECIA',
    'CH' => 'SUIZA',
    'SR' => 'SURINAM',
    'TH' => 'TAILANDIA',
    'TW' => 'TAIWÁN',
    'TZ' => 'TANZANIA',
    'TJ' => 'TAYIKISTÁN',
    'IO' => 'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO',
    'TL' => 'TIMOR-LESTE',
    'TG' => 'TOGO',
    'TK' => 'TOKELAU',
    'TO' => 'TONGA',
    'TT' => 'TRINIDAD Y TOBAGO',
    'TN' => 'TÚNEZ',
    'TM' => 'TURKMENISTÁN',
    'TR' => 'TURQUÍA',
    'TV' => 'TUVALU',
    'UA' => 'UCRANIA',
    'UG' => 'UGANDA',
    'UY' => 'URUGUAY',
    'UZ' => 'UZBEKISTÁN',
    'VU' => 'VANUATU',
    'VE' => 'VENEZUELA',
    'VN' => 'VIETNAM',
    'YE' => 'YEMEN',
    'DJ' => 'YIBUTI',
    'ZM' => 'ZAMBIA',
    'ZW' => 'ZIMBABWE',
];

$TCV_CATALOGOS['actividad_economica'] = $DIN_CATALOGOS['actividad_economica'] ?? [
    '1000000' => 'NO APLICA',
];

$TCV_CATALOGOS['giro_mercantil'] = $DIN_CATALOGOS['giro_mercantil'] ?? [
    '1000000' => 'NO APLICA',
];

if (!function_exists('tcvCatalogoOptions')) {
    function tcvCatalogoOptions(string $key, ?string $selected = null, ?callable $labeler = null, bool $withPlaceholder = true): string
    {
        global $TCV_CATALOGOS;
        $items = $TCV_CATALOGOS[$key] ?? [];
        $html = $withPlaceholder ? '<option value="">-- Seleccione --</option>' : '';
        foreach ($items as $k => $v) {
            $label = $labeler ? $labeler((string)$k, (string)$v) : ((string)$k . ' - ' . (string)$v);
            $sel = ((string)$selected === (string)$k) ? ' selected' : '';
            $html .= '<option value="' . htmlspecialchars((string)$k, ENT_QUOTES, 'UTF-8') . '"' . $sel . '>'
                . htmlspecialchars($label, ENT_QUOTES, 'UTF-8') . '</option>';
        }
        return $html;
    }
}
